# Crime analysis assignment

Ashlyn O'Hara
Chase Davis, James Gordon, Mike Jenner

Advanced Data Journalism
20 November 2019

Your job for this assignment is pretty wide open. Just take the `campus_crime.csv` file included in this directory and use some analysis tools from Pandas and Seaborn to explore it. There is no right answer here. Just use the tools we've discussed to look through the data and come up with **three story ideas**.

Note: If you want to use some of your own data instead, go for it!

Your assignment should be checked in to your Github repository in the form of a Jupyter notebook. It is due **Monday, Dec. 2** (the Monday after break).

# My story ideas

-Relationship between size of student body and number of violent crimes. 
-Why Florida State University is an outlier when it comes to manslaughters (it is the only school on the list where 'manslaughter' = True)
-Burglaries seem to be the most common crime. Why? Any ties to college students being poor?

## Your code here

In [21]:
import agate
import agatestats
import csv

In [22]:
crime_analysis = agate.Table.from_csv('campus_crime.csv')

In [23]:
print(crime_analysis)

| column       | data_type |
| ------------ | --------- |
| instname     | Text      |
| total_enr    | Number    |
| murder       | Number    |
| manslaughter | Boolean   |
| forcible     | Number    |
| nonforce     | Number    |
| robbery      | Number    |
| agg_aslt     | Number    |
| burglary     | Number    |
| vehicle      | Number    |
| arson        | Number    |

In [24]:
inst_enrollment = crime_analysis.order_by('total_enr', reverse = True)

In [25]:
inst_enrollment.print_table(max_rows = None)

| instname             | total_enr | murder | manslaughter | forcible | nonforce | ... |
| -------------------- | --------- | ------ | ------------ | -------- | -------- | --- |
| Houston Community... | 1,323,315 |      0 |        False |        0 |        0 | ... |
| Austin Community ... | 1,082,400 |      0 |        False |        0 |        0 | ... |
| University of Cen... |   935,440 |      0 |        False |        6 |        0 | ... |
| New York University  |   658,665 |      0 |        False |        1 |        0 | ... |
| Miami Dade College   |   509,888 |      0 |        False |        0 |        0 | ... |
| Purdue University... |   449,339 |      0 |        False |        7 |        0 | ... |
| Pima Community Co... |   443,628 |      0 |        False |        0 |        0 | ... |
| Broward College      |   379,782 |      0 |        False |        0 |        0 | ... |
| Lone Star College... |   378,174 |      0 |        False |        0 |        1 | ... |
| Virginia Polytech... |   371,232 |      1 |        False |       14 |        0 | ... |
| University of Sou... |   342,090 |      0 |        False |        8 |        0 | ... |
| Valencia College     |   341,048 |      0 |        False |        0 |        0 | ... |
| Tarrant County Co... |   300,372 |      0 |        False |        0 |        0 | ... |
| Northern Virginia... |   300,264 |      0 |        False |        2 |        0 | ... |
| Temple University    |   294,840 |      0 |        False |        4 |        0 | ... |
| Arizona State Uni... |   289,016 |      0 |        False |       17 |        1 | ... |
| Des Moines Area C... |   279,675 |      0 |        False |        0 |        0 | ... |
| DeVry University-... |   279,210 |      0 |        False |        0 |        0 | ... |
| Portland Communit... |   277,056 |      0 |        False |        5 |        0 | ... |
| St Petersburg Col... |   265,024 |      0 |        False |        0 |        1 | ... |
| University of Mar... |   256,278 |      0 |        False |        0 |        0 | ... |
| Rio Salado College   |   251,090 |      0 |        False |        0 |        0 | ... |
| Western Michigan ... |   250,860 |      0 |        False |        3 |        1 | ... |
| Columbus State Co... |   247,368 |      0 |        False |        0 |        0 | ... |
| Florida State Col... |   246,904 |      0 |        False |        0 |        0 | ... |
| Florida Atlantic ... |   233,968 |      0 |        False |        1 |        0 | ... |
| Texas Tech Univer... |   226,289 |      0 |        False |        3 |        0 | ... |
| Tidewater Communi... |   224,707 |      0 |        False |        0 |        0 | ... |
| Cuyahoga Communit... |   215,971 |      0 |        False |        3 |        0 | ... |
| El Paso Community... |   215,061 |      0 |        False |        0 |        0 | ... |
| Eastern Michigan ... |   210,771 |      0 |        False |        4 |        0 | ... |
| Johns Hopkins Uni... |   209,960 |      0 |        False |        0 |        0 | ... |
| Troy University      |   209,376 |      0 |        False |        0 |        0 | ... |
| George Washington... |   202,080 |      0 |        False |       16 |        0 | ... |
| Salt Lake Communi... |   200,520 |      0 |        False |        1 |        0 | ... |
| Michigan State Un... |   191,300 |      0 |        False |       15 |        0 | ... |
| Saint Louis Commu... |   175,200 |      0 |        False |        0 |        0 | ... |
| Brigham Young Uni... |   170,505 |      0 |        False |        0 |        0 | ... |
| Central New Mexic... |   166,062 |      0 |        False |        3 |        0 | ... |
| Delgado Community... |   163,488 |      0 |        False |        0 |        0 | ... |
| University of Ken... |   163,356 |      0 |        False |        5 |        0 | ... |
| The Community Col... |   157,626 |      0 |        False |        1 |        0 | ... |
| College of DuPage    |   157,254 |      0 |        False |        0 |        0 | ... |
| DePaul University    |   152,388 |      0 |        False |        1 |        0 | ... |
| Drexel University    |   149,160 |      0 |        False |        5 |        0 | ... |
| University of Pen... |   148,992 |      0 |        False |       12 |        0 | ... |
| St John's Univers... |   147,469 |      0 |        False |        5 |        0 | ... |
| Syracuse University  |   145,803 |      0 |        False |       12 |        0 | ... |
| Oakland Community... |   145,790 |      0 |        False |        2 |        0 | ... |
| University of Vir... |   145,782 |      0 |        False |       13 |        0 | ... |
| California State ... |   144,624 |      0 |        False |        0 |        0 | ... |
| Hillsborough Comm... |   141,645 |      0 |        False |        0 |        0 | ... |
| CUNY Hunter College  |   136,932 |      0 |        False |        0 |        0 | ... |
| Georgia Perimeter... |   134,980 |      0 |        False |        0 |        0 | ... |
| Western Kentucky ... |   126,216 |      0 |        False |        5 |        0 | ... |
| Grand Valley Stat... |   123,310 |      0 |        False |        2 |        0 | ... |
| Wayne State Unive... |   123,060 |      0 |        False |        2 |        0 | ... |
| Wayne County Comm... |   122,640 |      0 |        False |        1 |        0 | ... |
| University of Hou... |   119,460 |      0 |        False |        6 |        0 | ... |
| University of Iowa   |   119,240 |      0 |        False |       10 |        0 | ... |
| Palm Beach State ... |   117,416 |      0 |        False |        0 |        0 | ... |
| Northern Illinois... |   114,950 |      0 |        False |        4 |        0 | ... |
| College of Southe... |   113,151 |      0 |        False |        2 |        0 | ... |
| Harrisburg Area C... |   112,975 |      0 |        False |        1 |        0 | ... |
| University of Kansas |   111,756 |      0 |        False |        4 |        0 | ... |
| Washington State ... |   109,316 |      0 |        False |        8 |        0 | ... |
| Suffolk County Co... |   107,148 |      0 |        False |        0 |        0 | ... |
| Sinclair Communit... |   105,530 |      0 |        False |        0 |        0 | ... |
| University of Min... |   105,114 |      0 |        False |       12 |        0 | ... |
| Northwestern Univ... |   104,795 |      0 |        False |        3 |        0 | ... |
| Columbia Universi... |   104,200 |      0 |        False |        4 |        0 | ... |
| Texas A & M Unive... |   100,460 |      0 |        False |        3 |        0 | ... |
| The University of... |   100,317 |      0 |        False |        2 |        0 | ... |
| University of Flo... |    99,178 |      0 |        False |       10 |        0 | ... |
| American River Co... |    95,250 |      0 |        False |        1 |        2 | ... |
| Virginia Commonwe... |    94,881 |      0 |        False |        6 |        0 | ... |
| University of Mem... |    90,900 |      0 |        False |        2 |        0 | ... |
| The University of... |    90,582 |      0 |        False |        4 |        0 | ... |
| University of Ill... |    88,814 |      0 |        False |        5 |        0 | ... |
| San Jacinto Commu... |    88,176 |      0 |        False |        0 |        0 | ... |
| Nova Southeastern... |    85,371 |      0 |        False |        2 |        1 | ... |
| University of Ill... |    84,273 |      1 |        False |        9 |        0 | ... |
| Collin County Com... |    82,779 |      0 |        False |        0 |        0 | ... |
| Front Range Commu... |    82,272 |      0 |        False |        0 |        0 | ... |
| Community College... |    81,720 |      0 |        False |        0 |        0 | ... |
| Southwestern College |    81,636 |      0 |        False |        0 |        0 | ... |
| Montgomery College   |    80,988 |      0 |        False |        4 |        0 | ... |
| Central Texas Col... |    80,985 |      0 |        False |        0 |        0 | ... |
| Tulsa Community C... |    80,616 |      0 |        False |        0 |        0 | ... |
| Mesa Community Co... |    77,085 |      0 |        False |        0 |        0 | ... |
| University of Nor... |    75,636 |      0 |        False |        2 |        0 | ... |
| University of Mar... |    75,262 |      0 |        False |        4 |        0 | ... |
| Ashford University   |    74,596 |      0 |        False |        2 |        0 | ... |
| University of Oregon |    73,188 |      0 |        False |        8 |        0 | ... |
| Santa Rosa Junior... |    72,597 |      0 |        False |        0 |        0 | ... |
| Sacramento City C... |    72,318 |      0 |        False |        1 |        0 | ... |
| University of Cal... |    72,274 |      0 |        False |       30 |        1 | ... |
| Texas State Unive... |    68,174 |      0 |        False |        3 |        0 | ... |
| University of Toledo |    67,830 |      0 |        False |        2 |        0 | ... |
| University of Cin... |    66,658 |      0 |        False |        9 |        0 | ... |
| Boston University    |    64,878 |      0 |        False |        6 |        0 | ... |
| University of Del... |    64,467 |      0 |        False |        3 |        1 | ... |
| Liberty University   |    64,096 |      0 |        False |        4 |        0 | ... |
| Georgia State Uni... |    64,044 |      0 |        False |        4 |        0 | ... |
| University of Cal... |    63,464 |      0 |        False |       24 |        0 | ... |
| University of Lou... |    63,456 |      0 |        False |        0 |        0 | ... |
| The University of... |    63,294 |      0 |        False |        3 |        0 | ... |
| The University of... |    61,936 |      0 |        False |        2 |        0 | ... |
| Indiana Universit... |    61,060 |      0 |        False |        2 |        0 | ... |
| San Jose State Un... |    60,472 |      2 |        False |        3 |        0 | ... |
| Ohio State Univer... |    56,867 |      0 |        False |       28 |        0 | ... |
| Kaplan University... |    56,606 |      0 |        False |        0 |        0 | ... |
| University of Akr... |    54,940 |      0 |        False |        5 |        0 | ... |
| Harvard University   |    54,784 |      0 |        False |       21 |        0 | ... |
| East Carolina Uni... |    54,772 |      0 |        False |        9 |        0 | ... |
| University of Nev... |    54,728 |      0 |        False |        1 |        0 | ... |
| University of Cal... |    54,378 |      0 |        False |        6 |        1 | ... |
| Pasadena City Col... |    52,114 |      0 |        False |        2 |        0 | ... |
| University of Con... |    51,736 |      0 |        False |        8 |        0 | ... |
| Long Beach City C... |    51,564 |      0 |        False |        0 |        0 | ... |
| The University of... |    51,112 |      0 |        False |        2 |        0 | ... |
| Palomar College      |    50,854 |      0 |        False |        1 |        0 | ... |
| Walden University    |    48,982 |      0 |        False |        0 |        0 | ... |
| Oklahoma State Un... |    48,780 |      0 |        False |       11 |        0 | ... |
| Macomb Community ... |    47,938 |      0 |        False |        0 |        0 | ... |
| Kansas State Univ... |    47,726 |      0 |        False |        7 |        0 | ... |
| Pennsylvania Stat... |    45,628 |      0 |        False |       24 |        0 | ... |
| University of Col... |    44,990 |      0 |        False |        1 |        0 | ... |
| Florida Internati... |    44,616 |      0 |        False |        3 |        0 | ... |
| Ball State Univer... |    44,294 |      0 |        False |        8 |        0 | ... |
| Glendale Communit... |    42,752 |      0 |        False |        0 |        0 | ... |
| Indiana Universit... |    42,731 |      0 |        False |       11 |        0 | ... |
| University of Mic... |    42,716 |      0 |        False |       14 |        0 | ... |
| University of Was... |    42,444 |      0 |        False |        5 |        0 | ... |
| Ivy Tech Communit... |    42,092 |      0 |        False |        0 |        0 | ... |
| University of Wis... |    41,946 |      0 |        False |       24 |        0 | ... |
| Georgia Institute... |    41,882 |      0 |        False |        5 |        0 | ... |
| Lansing Community... |    41,280 |      0 |        False |        0 |        0 | ... |
| Florida State Uni... |    41,087 |      0 |         True |        2 |        0 | ... |
| University of Haw... |    40,858 |      0 |        False |       12 |        0 | ... |
| Mississippi State... |    40,848 |      0 |        False |        1 |        0 | ... |
| Grand Canyon Univ... |    40,487 |      0 |        False |        1 |        0 | ... |
| Fresno City College  |    40,270 |      0 |        False |        0 |        0 | ... |
| Richland College     |    40,000 |      0 |        False |        0 |        0 | ... |
| Rutgers Universit... |    39,950 |      0 |        False |       12 |        0 | ... |
| University of Sou... |    39,596 |      0 |        False |        1 |        0 | ... |
| University of Cal... |    39,271 |      0 |        False |        8 |        0 | ... |
| University of Ari... |    39,236 |      1 |        False |        3 |        0 | ... |
| East Los Angeles ... |    37,057 |      0 |        False |        0 |        0 | ... |
| California State ... |    36,911 |      0 |        False |        1 |        0 | ... |
| Capella University   |    36,375 |      0 |        False |        0 |        0 | ... |
| Excelsior College    |    35,608 |      0 |        False |        0 |        0 | ... |
| California State ... |    34,870 |      0 |        False |        3 |        0 | ... |
| University of Geo... |    34,816 |      0 |        False |        5 |        0 | ... |
| North Carolina St... |    34,767 |      0 |        False |        7 |        0 | ... |
| City College of S... |    34,558 |      0 |        False |        1 |        0 | ... |
| University of Mis... |    33,762 |      0 |        False |       11 |        0 | ... |
| Utah Valley Unive... |    33,395 |      0 |        False |        3 |        0 | ... |
| George Mason Univ... |    33,320 |      0 |        False |        8 |        0 | ... |
| University of Col... |    32,558 |      0 |        False |        6 |        0 | ... |
| University of Utah   |    31,660 |      0 |        False |        5 |        0 | ... |
| University of Sou... |    30,721 |      0 |        False |        1 |        0 | ... |
| San Diego State U... |    30,541 |      0 |        False |        6 |        0 | ... |
| Colorado State Un... |    30,467 |      0 |        False |        4 |        0 | ... |
| Santa Ana College    |    30,289 |      0 |        False |        0 |        0 | ... |
| Santa Monica College |    29,971 |      0 |        False |        0 |        0 | ... |
| Louisiana State U... |    29,718 |      0 |        False |        2 |        0 | ... |
| West Virginia Uni... |    29,617 |      0 |        False |        4 |        0 | ... |
| Iowa State Univer... |    29,611 |      0 |        False |        6 |        0 | ... |
| South Texas College  |    29,604 |      0 |        False |        0 |        0 | ... |
| San Francisco Sta... |    29,541 |      0 |        False |        4 |        0 | ... |
| University of Wis... |    29,350 |      0 |        False |        3 |        0 | ... |
| University of Nor... |    29,137 |      0 |        False |       12 |        0 | ... |
| University of New... |    28,977 |      0 |        False |        2 |        0 | ... |
| University at Buf... |    28,849 |      0 |        False |        3 |        0 | ... |
| University of Pit... |    28,766 |      0 |        False |        4 |        0 | ... |
| University of Cal... |    28,593 |      0 |        False |        6 |        0 | ... |
| Portland State Un... |    28,584 |      0 |        False |        8 |        0 | ... |
| Mt. San Antonio C... |    28,388 |      0 |        False |        1 |        0 | ... |
| Central Michigan ... |    28,194 |      0 |        False |        5 |        0 | ... |
| University of Mas... |    28,084 |      0 |        False |       13 |        0 | ... |
| California State ... |    28,016 |      0 |        False |        2 |        0 | ... |
| Kent State Univer... |    27,855 |      0 |        False |        3 |        0 | ... |
| University of Okl... |    27,138 |      0 |        False |       13 |        0 | ... |
| Northeastern Univ... |    26,959 |      0 |        False |        6 |        0 | ... |
| Utah State Univer... |    26,757 |      0 |        False |        3 |        0 | ... |
| Middle Tennessee ... |    26,442 |      0 |        False |        4 |        0 | ... |
| Ohio University-M... |    26,201 |      0 |        False |        8 |        0 | ... |
| San Antonio College  |    25,567 |      0 |        False |        1 |        0 | ... |
| Everest Universit... |    25,537 |      0 |        False |        0 |        0 | ... |
| San Diego Mesa Co... |    25,504 |      0 |        False |        0 |        0 | ... |
| Auburn University    |    25,469 |      0 |        False |        1 |        0 | ... |
| Northern Arizona ... |    25,359 |      0 |        False |       13 |        0 | ... |
| Weber State Unive... |    25,301 |      0 |        False |        2 |        0 | ... |
| University of Nor... |    25,277 |      0 |        False |        2 |        0 | ... |
| Oregon State Univ... |    24,962 |      0 |        False |        3 |        0 | ... |
| Old Dominion Univ... |    24,753 |      0 |        False |        7 |        0 | ... |
| University of Neb... |    24,593 |      0 |        False |        3 |        0 | ... |
| CUNY Borough of M... |    24,463 |      0 |        False |        2 |        0 | ... |
| El Camino Communi... |    24,463 |      0 |        False |        0 |        0 | ... |
| De Anza College      |    24,187 |      0 |        False |        0 |        0 | ... |
| Kennesaw State Un... |    24,175 |      0 |        False |        2 |        0 | ... |
| Stony Brook Unive... |    23,920 |      0 |        False |       13 |        0 | ... |
| Metropolitan Stat... |    23,789 |      0 |        False |        1 |        0 | ... |
| Nassau Community ... |    23,550 |      0 |        False |        1 |        0 | ... |
| University of Ark... |    23,199 |      0 |        False |        5 |        0 | ... |
| Orange Coast College |    22,654 |      0 |        False |        1 |        0 | ... |
| The University of... |    22,640 |      0 |        False |        5 |        0 | ... |
| Saddleback College   |    22,578 |      0 |        False |        1 |        0 | ... |
| California State ... |    21,981 |      0 |        False |        1 |        0 | ... |
| University of Cal... |    21,685 |      0 |        False |        7 |        1 | ... |
| Towson University    |    21,464 |      0 |        False |        7 |        0 | ... |
| Cerritos College     |    21,335 |      0 |        False |        1 |        0 | ... |
| Illinois State Un... |    21,310 |      0 |        False |        2 |        0 | ... |
| California State ... |    21,284 |      0 |        False |        1 |        0 | ... |
| Cornell University   |    21,131 |      0 |        False |        7 |        0 | ... |
| California State ... |    21,107 |      0 |        False |        7 |        0 | ... |
| Los Angeles City ... |    21,028 |      0 |        False |        0 |        0 | ... |
| Johnson County Co... |    21,020 |      0 |        False |        1 |        0 | ... |
| CUNY Queens College  |    20,993 |      0 |        False |        0 |        0 | ... |
| University of Cal... |    20,900 |      0 |        False |        5 |        0 | ... |
| Instituto de Banc... |    20,876 |      0 |        False |        0 |        0 | ... |

In [27]:
outliers = inst_enrollment.stdev_outliers('forcible')

In [29]:
outliers.print_table(max_rows=None)

| instname             | total_enr | murder | manslaughter | forcible | nonforce | ... |
| -------------------- | --------- | ------ | ------------ | -------- | -------- | --- |
| Houston Community... | 1,323,315 |      0 |        False |        0 |        0 | ... |
| Austin Community ... | 1,082,400 |      0 |        False |        0 |        0 | ... |
| University of Cen... |   935,440 |      0 |        False |        6 |        0 | ... |
| New York University  |   658,665 |      0 |        False |        1 |        0 | ... |
| Miami Dade College   |   509,888 |      0 |        False |        0 |        0 | ... |
| Purdue University... |   449,339 |      0 |        False |        7 |        0 | ... |
| Pima Community Co... |   443,628 |      0 |        False |        0 |        0 | ... |
| Broward College      |   379,782 |      0 |        False |        0 |        0 | ... |
| Lone Star College... |   378,174 |      0 |        False |        0 |        1 | ... |
| Virginia Polytech... |   371,232 |      1 |        False |       14 |        0 | ... |
| University of Sou... |   342,090 |      0 |        False |        8 |        0 | ... |
| Valencia College     |   341,048 |      0 |        False |        0 |        0 | ... |
| Tarrant County Co... |   300,372 |      0 |        False |        0 |        0 | ... |
| Northern Virginia... |   300,264 |      0 |        False |        2 |        0 | ... |
| Temple University    |   294,840 |      0 |        False |        4 |        0 | ... |
| Arizona State Uni... |   289,016 |      0 |        False |       17 |        1 | ... |
| Des Moines Area C... |   279,675 |      0 |        False |        0 |        0 | ... |
| DeVry University-... |   279,210 |      0 |        False |        0 |        0 | ... |
| Portland Communit... |   277,056 |      0 |        False |        5 |        0 | ... |
| St Petersburg Col... |   265,024 |      0 |        False |        0 |        1 | ... |
| University of Mar... |   256,278 |      0 |        False |        0 |        0 | ... |
| Rio Salado College   |   251,090 |      0 |        False |        0 |        0 | ... |
| Western Michigan ... |   250,860 |      0 |        False |        3 |        1 | ... |
| Columbus State Co... |   247,368 |      0 |        False |        0 |        0 | ... |
| Florida State Col... |   246,904 |      0 |        False |        0 |        0 | ... |
| Florida Atlantic ... |   233,968 |      0 |        False |        1 |        0 | ... |
| Texas Tech Univer... |   226,289 |      0 |        False |        3 |        0 | ... |
| Tidewater Communi... |   224,707 |      0 |        False |        0 |        0 | ... |
| Cuyahoga Communit... |   215,971 |      0 |        False |        3 |        0 | ... |
| El Paso Community... |   215,061 |      0 |        False |        0 |        0 | ... |
| Eastern Michigan ... |   210,771 |      0 |        False |        4 |        0 | ... |
| Johns Hopkins Uni... |   209,960 |      0 |        False |        0 |        0 | ... |
| Troy University      |   209,376 |      0 |        False |        0 |        0 | ... |
| George Washington... |   202,080 |      0 |        False |       16 |        0 | ... |
| Salt Lake Communi... |   200,520 |      0 |        False |        1 |        0 | ... |
| Michigan State Un... |   191,300 |      0 |        False |       15 |        0 | ... |
| Saint Louis Commu... |   175,200 |      0 |        False |        0 |        0 | ... |
| Brigham Young Uni... |   170,505 |      0 |        False |        0 |        0 | ... |
| Central New Mexic... |   166,062 |      0 |        False |        3 |        0 | ... |
| Delgado Community... |   163,488 |      0 |        False |        0 |        0 | ... |
| University of Ken... |   163,356 |      0 |        False |        5 |        0 | ... |
| The Community Col... |   157,626 |      0 |        False |        1 |        0 | ... |
| College of DuPage    |   157,254 |      0 |        False |        0 |        0 | ... |
| DePaul University    |   152,388 |      0 |        False |        1 |        0 | ... |
| Drexel University    |   149,160 |      0 |        False |        5 |        0 | ... |
| University of Pen... |   148,992 |      0 |        False |       12 |        0 | ... |
| St John's Univers... |   147,469 |      0 |        False |        5 |        0 | ... |
| Syracuse University  |   145,803 |      0 |        False |       12 |        0 | ... |
| Oakland Community... |   145,790 |      0 |        False |        2 |        0 | ... |
| University of Vir... |   145,782 |      0 |        False |       13 |        0 | ... |
| California State ... |   144,624 |      0 |        False |        0 |        0 | ... |
| Hillsborough Comm... |   141,645 |      0 |        False |        0 |        0 | ... |
| CUNY Hunter College  |   136,932 |      0 |        False |        0 |        0 | ... |
| Georgia Perimeter... |   134,980 |      0 |        False |        0 |        0 | ... |
| Western Kentucky ... |   126,216 |      0 |        False |        5 |        0 | ... |
| Grand Valley Stat... |   123,310 |      0 |        False |        2 |        0 | ... |
| Wayne State Unive... |   123,060 |      0 |        False |        2 |        0 | ... |
| Wayne County Comm... |   122,640 |      0 |        False |        1 |        0 | ... |
| University of Hou... |   119,460 |      0 |        False |        6 |        0 | ... |
| University of Iowa   |   119,240 |      0 |        False |       10 |        0 | ... |
| Palm Beach State ... |   117,416 |      0 |        False |        0 |        0 | ... |
| Northern Illinois... |   114,950 |      0 |        False |        4 |        0 | ... |
| College of Southe... |   113,151 |      0 |        False |        2 |        0 | ... |
| Harrisburg Area C... |   112,975 |      0 |        False |        1 |        0 | ... |
| University of Kansas |   111,756 |      0 |        False |        4 |        0 | ... |
| Washington State ... |   109,316 |      0 |        False |        8 |        0 | ... |
| Suffolk County Co... |   107,148 |      0 |        False |        0 |        0 | ... |
| Sinclair Communit... |   105,530 |      0 |        False |        0 |        0 | ... |
| University of Min... |   105,114 |      0 |        False |       12 |        0 | ... |
| Northwestern Univ... |   104,795 |      0 |        False |        3 |        0 | ... |
| Columbia Universi... |   104,200 |      0 |        False |        4 |        0 | ... |
| Texas A & M Unive... |   100,460 |      0 |        False |        3 |        0 | ... |
| The University of... |   100,317 |      0 |        False |        2 |        0 | ... |
| University of Flo... |    99,178 |      0 |        False |       10 |        0 | ... |
| American River Co... |    95,250 |      0 |        False |        1 |        2 | ... |
| Virginia Commonwe... |    94,881 |      0 |        False |        6 |        0 | ... |
| University of Mem... |    90,900 |      0 |        False |        2 |        0 | ... |
| The University of... |    90,582 |      0 |        False |        4 |        0 | ... |
| University of Ill... |    88,814 |      0 |        False |        5 |        0 | ... |
| San Jacinto Commu... |    88,176 |      0 |        False |        0 |        0 | ... |
| Nova Southeastern... |    85,371 |      0 |        False |        2 |        1 | ... |
| University of Ill... |    84,273 |      1 |        False |        9 |        0 | ... |
| Collin County Com... |    82,779 |      0 |        False |        0 |        0 | ... |
| Front Range Commu... |    82,272 |      0 |        False |        0 |        0 | ... |
| Community College... |    81,720 |      0 |        False |        0 |        0 | ... |
| Southwestern College |    81,636 |      0 |        False |        0 |        0 | ... |
| Montgomery College   |    80,988 |      0 |        False |        4 |        0 | ... |
| Central Texas Col... |    80,985 |      0 |        False |        0 |        0 | ... |
| Tulsa Community C... |    80,616 |      0 |        False |        0 |        0 | ... |
| Mesa Community Co... |    77,085 |      0 |        False |        0 |        0 | ... |
| University of Nor... |    75,636 |      0 |        False |        2 |        0 | ... |
| University of Mar... |    75,262 |      0 |        False |        4 |        0 | ... |
| Ashford University   |    74,596 |      0 |        False |        2 |        0 | ... |
| University of Oregon |    73,188 |      0 |        False |        8 |        0 | ... |
| Santa Rosa Junior... |    72,597 |      0 |        False |        0 |        0 | ... |
| Sacramento City C... |    72,318 |      0 |        False |        1 |        0 | ... |
| Texas State Unive... |    68,174 |      0 |        False |        3 |        0 | ... |
| University of Toledo |    67,830 |      0 |        False |        2 |        0 | ... |
| University of Cin... |    66,658 |      0 |        False |        9 |        0 | ... |
| Boston University    |    64,878 |      0 |        False |        6 |        0 | ... |
| University of Del... |    64,467 |      0 |        False |        3 |        1 | ... |
| Liberty University   |    64,096 |      0 |        False |        4 |        0 | ... |
| Georgia State Uni... |    64,044 |      0 |        False |        4 |        0 | ... |
| University of Lou... |    63,456 |      0 |        False |        0 |        0 | ... |
| The University of... |    63,294 |      0 |        False |        3 |        0 | ... |
| The University of... |    61,936 |      0 |        False |        2 |        0 | ... |
| Indiana Universit... |    61,060 |      0 |        False |        2 |        0 | ... |
| San Jose State Un... |    60,472 |      2 |        False |        3 |        0 | ... |
| Kaplan University... |    56,606 |      0 |        False |        0 |        0 | ... |
| University of Akr... |    54,940 |      0 |        False |        5 |        0 | ... |
| East Carolina Uni... |    54,772 |      0 |        False |        9 |        0 | ... |
| University of Nev... |    54,728 |      0 |        False |        1 |        0 | ... |
| University of Cal... |    54,378 |      0 |        False |        6 |        1 | ... |
| Pasadena City Col... |    52,114 |      0 |        False |        2 |        0 | ... |
| University of Con... |    51,736 |      0 |        False |        8 |        0 | ... |
| Long Beach City C... |    51,564 |      0 |        False |        0 |        0 | ... |
| The University of... |    51,112 |      0 |        False |        2 |        0 | ... |
| Palomar College      |    50,854 |      0 |        False |        1 |        0 | ... |
| Walden University    |    48,982 |      0 |        False |        0 |        0 | ... |
| Oklahoma State Un... |    48,780 |      0 |        False |       11 |        0 | ... |
| Macomb Community ... |    47,938 |      0 |        False |        0 |        0 | ... |
| Kansas State Univ... |    47,726 |      0 |        False |        7 |        0 | ... |
| University of Col... |    44,990 |      0 |        False |        1 |        0 | ... |
| Florida Internati... |    44,616 |      0 |        False |        3 |        0 | ... |
| Ball State Univer... |    44,294 |      0 |        False |        8 |        0 | ... |
| Glendale Communit... |    42,752 |      0 |        False |        0 |        0 | ... |
| Indiana Universit... |    42,731 |      0 |        False |       11 |        0 | ... |
| University of Mic... |    42,716 |      0 |        False |       14 |        0 | ... |
| University of Was... |    42,444 |      0 |        False |        5 |        0 | ... |
| Ivy Tech Communit... |    42,092 |      0 |        False |        0 |        0 | ... |
| Georgia Institute... |    41,882 |      0 |        False |        5 |        0 | ... |
| Lansing Community... |    41,280 |      0 |        False |        0 |        0 | ... |
| Florida State Uni... |    41,087 |      0 |         True |        2 |        0 | ... |
| University of Haw... |    40,858 |      0 |        False |       12 |        0 | ... |
| Mississippi State... |    40,848 |      0 |        False |        1 |        0 | ... |
| Grand Canyon Univ... |    40,487 |      0 |        False |        1 |        0 | ... |
| Fresno City College  |    40,270 |      0 |        False |        0 |        0 | ... |
| Richland College     |    40,000 |      0 |        False |        0 |        0 | ... |
| Rutgers Universit... |    39,950 |      0 |        False |       12 |        0 | ... |
| University of Sou... |    39,596 |      0 |        False |        1 |        0 | ... |
| University of Cal... |    39,271 |      0 |        False |        8 |        0 | ... |
| University of Ari... |    39,236 |      1 |        False |        3 |        0 | ... |
| East Los Angeles ... |    37,057 |      0 |        False |        0 |        0 | ... |
| California State ... |    36,911 |      0 |        False |        1 |        0 | ... |
| Capella University   |    36,375 |      0 |        False |        0 |        0 | ... |
| Excelsior College    |    35,608 |      0 |        False |        0 |        0 | ... |
| California State ... |    34,870 |      0 |        False |        3 |        0 | ... |
| University of Geo... |    34,816 |      0 |        False |        5 |        0 | ... |
| North Carolina St... |    34,767 |      0 |        False |        7 |        0 | ... |
| City College of S... |    34,558 |      0 |        False |        1 |        0 | ... |
| University of Mis... |    33,762 |      0 |        False |       11 |        0 | ... |
| Utah Valley Unive... |    33,395 |      0 |        False |        3 |        0 | ... |
| George Mason Univ... |    33,320 |      0 |        False |        8 |        0 | ... |
| University of Col... |    32,558 |      0 |        False |        6 |        0 | ... |
| University of Utah   |    31,660 |      0 |        False |        5 |        0 | ... |
| University of Sou... |    30,721 |      0 |        False |        1 |        0 | ... |
| San Diego State U... |    30,541 |      0 |        False |        6 |        0 | ... |
| Colorado State Un... |    30,467 |      0 |        False |        4 |        0 | ... |
| Santa Ana College    |    30,289 |      0 |        False |        0 |        0 | ... |
| Santa Monica College |    29,971 |      0 |        False |        0 |        0 | ... |
| Louisiana State U... |    29,718 |      0 |        False |        2 |        0 | ... |
| West Virginia Uni... |    29,617 |      0 |        False |        4 |        0 | ... |
| Iowa State Univer... |    29,611 |      0 |        False |        6 |        0 | ... |
| South Texas College  |    29,604 |      0 |        False |        0 |        0 | ... |
| San Francisco Sta... |    29,541 |      0 |        False |        4 |        0 | ... |
| University of Wis... |    29,350 |      0 |        False |        3 |        0 | ... |
| University of Nor... |    29,137 |      0 |        False |       12 |        0 | ... |
| University of New... |    28,977 |      0 |        False |        2 |        0 | ... |
| University at Buf... |    28,849 |      0 |        False |        3 |        0 | ... |
| University of Pit... |    28,766 |      0 |        False |        4 |        0 | ... |
| University of Cal... |    28,593 |      0 |        False |        6 |        0 | ... |
| Portland State Un... |    28,584 |      0 |        False |        8 |        0 | ... |
| Mt. San Antonio C... |    28,388 |      0 |        False |        1 |        0 | ... |
| Central Michigan ... |    28,194 |      0 |        False |        5 |        0 | ... |
| University of Mas... |    28,084 |      0 |        False |       13 |        0 | ... |
| California State ... |    28,016 |      0 |        False |        2 |        0 | ... |
| Kent State Univer... |    27,855 |      0 |        False |        3 |        0 | ... |
| University of Okl... |    27,138 |      0 |        False |       13 |        0 | ... |
| Northeastern Univ... |    26,959 |      0 |        False |        6 |        0 | ... |
| Utah State Univer... |    26,757 |      0 |        False |        3 |        0 | ... |
| Middle Tennessee ... |    26,442 |      0 |        False |        4 |        0 | ... |
| Ohio University-M... |    26,201 |      0 |        False |        8 |        0 | ... |
| San Antonio College  |    25,567 |      0 |        False |        1 |        0 | ... |
| Everest Universit... |    25,537 |      0 |        False |        0 |        0 | ... |
| San Diego Mesa Co... |    25,504 |      0 |        False |        0 |        0 | ... |
| Auburn University    |    25,469 |      0 |        False |        1 |        0 | ... |
| Northern Arizona ... |    25,359 |      0 |        False |       13 |        0 | ... |
| Weber State Unive... |    25,301 |      0 |        False |        2 |        0 | ... |
| University of Nor... |    25,277 |      0 |        False |        2 |        0 | ... |
| Oregon State Univ... |    24,962 |      0 |        False |        3 |        0 | ... |
| Old Dominion Univ... |    24,753 |      0 |        False |        7 |        0 | ... |
| University of Neb... |    24,593 |      0 |        False |        3 |        0 | ... |
| CUNY Borough of M... |    24,463 |      0 |        False |        2 |        0 | ... |
| El Camino Communi... |    24,463 |      0 |        False |        0 |        0 | ... |
| De Anza College      |    24,187 |      0 |        False |        0 |        0 | ... |
| Kennesaw State Un... |    24,175 |      0 |        False |        2 |        0 | ... |
| Stony Brook Unive... |    23,920 |      0 |        False |       13 |        0 | ... |
| Metropolitan Stat... |    23,789 |      0 |        False |        1 |        0 | ... |
| Nassau Community ... |    23,550 |      0 |        False |        1 |        0 | ... |
| University of Ark... |    23,199 |      0 |        False |        5 |        0 | ... |
| Orange Coast College |    22,654 |      0 |        False |        1 |        0 | ... |
| The University of... |    22,640 |      0 |        False |        5 |        0 | ... |
| Saddleback College   |    22,578 |      0 |        False |        1 |        0 | ... |
| California State ... |    21,981 |      0 |        False |        1 |        0 | ... |
| University of Cal... |    21,685 |      0 |        False |        7 |        1 | ... |
| Towson University    |    21,464 |      0 |        False |        7 |        0 | ... |
| Cerritos College     |    21,335 |      0 |        False |        1 |        0 | ... |
| Illinois State Un... |    21,310 |      0 |        False |        2 |        0 | ... |
| California State ... |    21,284 |      0 |        False |        1 |        0 | ... |
| Cornell University   |    21,131 |      0 |        False |        7 |        0 | ... |
| California State ... |    21,107 |      0 |        False |        7 |        0 | ... |
| Los Angeles City ... |    21,028 |      0 |        False |        0 |        0 | ... |
| Johnson County Co... |    21,020 |      0 |        False |        1 |        0 | ... |
| CUNY Queens College  |    20,993 |      0 |        False |        0 |        0 | ... |
| University of Cal... |    20,900 |      0 |        False |        5 |        0 | ... |
| Instituto de Banc... |    20,876 |      0 |        False |        0 |        0 | ... |
| Los Angeles Pierc... |    20,506 |      0 |        False |        4 |        0 | ... |
| Diablo Valley Col... |    20,310 |      0 |        False |        0 |        0 | ... |
| Missouri State Un... |    20,276 |      0 |        False |        0 |        0 | ... |
| Thomas Edison Sta... |    20,251 |      0 |        False |        0 |        0 | ... |
| Georgia Southern ... |    20,212 |      0 |        False |        3 |        0 | ... |
| Full Sail University |    20,160 |      0 |        False |        0 |        0 | ... |

In [30]:
murder_outliers = crime_analysis.order_by('murder', reverse = True)

In [31]:
murder_outliers.print_table(max_rows=None)

| instname             | total_enr | murder | manslaughter | forcible | nonforce | ... |
| -------------------- | --------- | ------ | ------------ | -------- | -------- | --- |
| San Jose State Un... |    60,472 |      2 |        False |        3 |        0 | ... |
| University of Ari... |    39,236 |      1 |        False |        3 |        0 | ... |
| University of Ill... |    84,273 |      1 |        False |        9 |        0 | ... |
| Virginia Polytech... |   371,232 |      1 |        False |       14 |        0 | ... |
| American River Co... |    95,250 |      0 |        False |        1 |        2 | ... |
| Arizona State Uni... |   289,016 |      0 |        False |       17 |        1 | ... |
| Ashford University   |    74,596 |      0 |        False |        2 |        0 | ... |
| Auburn University    |    25,469 |      0 |        False |        1 |        0 | ... |
| Austin Community ... | 1,082,400 |      0 |        False |        0 |        0 | ... |
| Ball State Univer... |    44,294 |      0 |        False |        8 |        0 | ... |
| Boston University    |    64,878 |      0 |        False |        6 |        0 | ... |
| Brigham Young Uni... |   170,505 |      0 |        False |        0 |        0 | ... |
| Broward College      |   379,782 |      0 |        False |        0 |        0 | ... |
| California State ... |    21,107 |      0 |        False |        7 |        0 | ... |
| California State ... |    21,981 |      0 |        False |        1 |        0 | ... |
| California State ... |   144,624 |      0 |        False |        0 |        0 | ... |
| California State ... |    34,870 |      0 |        False |        3 |        0 | ... |
| California State ... |    21,284 |      0 |        False |        1 |        0 | ... |
| California State ... |    36,911 |      0 |        False |        1 |        0 | ... |
| California State ... |    28,016 |      0 |        False |        2 |        0 | ... |
| Capella University   |    36,375 |      0 |        False |        0 |        0 | ... |
| Central Michigan ... |    28,194 |      0 |        False |        5 |        0 | ... |
| Central New Mexic... |   166,062 |      0 |        False |        3 |        0 | ... |
| Central Texas Col... |    80,985 |      0 |        False |        0 |        0 | ... |
| Cerritos College     |    21,335 |      0 |        False |        1 |        0 | ... |
| City College of S... |    34,558 |      0 |        False |        1 |        0 | ... |
| College of DuPage    |   157,254 |      0 |        False |        0 |        0 | ... |
| College of Southe... |   113,151 |      0 |        False |        2 |        0 | ... |
| Collin County Com... |    82,779 |      0 |        False |        0 |        0 | ... |
| Colorado State Un... |    30,467 |      0 |        False |        4 |        0 | ... |
| Columbia Universi... |   104,200 |      0 |        False |        4 |        0 | ... |
| Columbus State Co... |   247,368 |      0 |        False |        0 |        0 | ... |
| Community College... |    81,720 |      0 |        False |        0 |        0 | ... |
| Cornell University   |    21,131 |      0 |        False |        7 |        0 | ... |
| CUNY Borough of M... |    24,463 |      0 |        False |        2 |        0 | ... |
| CUNY Hunter College  |   136,932 |      0 |        False |        0 |        0 | ... |
| CUNY Queens College  |    20,993 |      0 |        False |        0 |        0 | ... |
| Cuyahoga Communit... |   215,971 |      0 |        False |        3 |        0 | ... |
| De Anza College      |    24,187 |      0 |        False |        0 |        0 | ... |
| Delgado Community... |   163,488 |      0 |        False |        0 |        0 | ... |
| DePaul University    |   152,388 |      0 |        False |        1 |        0 | ... |
| Des Moines Area C... |   279,675 |      0 |        False |        0 |        0 | ... |
| DeVry University-... |   279,210 |      0 |        False |        0 |        0 | ... |
| Diablo Valley Col... |    20,310 |      0 |        False |        0 |        0 | ... |
| Drexel University    |   149,160 |      0 |        False |        5 |        0 | ... |
| East Carolina Uni... |    54,772 |      0 |        False |        9 |        0 | ... |
| East Los Angeles ... |    37,057 |      0 |        False |        0 |        0 | ... |
| Eastern Michigan ... |   210,771 |      0 |        False |        4 |        0 | ... |
| El Camino Communi... |    24,463 |      0 |        False |        0 |        0 | ... |
| El Paso Community... |   215,061 |      0 |        False |        0 |        0 | ... |
| Everest Universit... |    25,537 |      0 |        False |        0 |        0 | ... |
| Excelsior College    |    35,608 |      0 |        False |        0 |        0 | ... |
| Florida Atlantic ... |   233,968 |      0 |        False |        1 |        0 | ... |
| Florida Internati... |    44,616 |      0 |        False |        3 |        0 | ... |
| Florida State Col... |   246,904 |      0 |        False |        0 |        0 | ... |
| Florida State Uni... |    41,087 |      0 |         True |        2 |        0 | ... |
| Fresno City College  |    40,270 |      0 |        False |        0 |        0 | ... |
| Front Range Commu... |    82,272 |      0 |        False |        0 |        0 | ... |
| Full Sail University |    20,160 |      0 |        False |        0 |        0 | ... |
| George Mason Univ... |    33,320 |      0 |        False |        8 |        0 | ... |
| George Washington... |   202,080 |      0 |        False |       16 |        0 | ... |
| Georgia Institute... |    41,882 |      0 |        False |        5 |        0 | ... |
| Georgia Perimeter... |   134,980 |      0 |        False |        0 |        0 | ... |
| Georgia Southern ... |    20,212 |      0 |        False |        3 |        0 | ... |
| Georgia State Uni... |    64,044 |      0 |        False |        4 |        0 | ... |
| Glendale Communit... |    42,752 |      0 |        False |        0 |        0 | ... |
| Grand Canyon Univ... |    40,487 |      0 |        False |        1 |        0 | ... |
| Grand Valley Stat... |   123,310 |      0 |        False |        2 |        0 | ... |
| Harrisburg Area C... |   112,975 |      0 |        False |        1 |        0 | ... |
| Harvard University   |    54,784 |      0 |        False |       21 |        0 | ... |
| Hillsborough Comm... |   141,645 |      0 |        False |        0 |        0 | ... |
| Houston Community... | 1,323,315 |      0 |        False |        0 |        0 | ... |
| Illinois State Un... |    21,310 |      0 |        False |        2 |        0 | ... |
| Indiana Universit... |    42,731 |      0 |        False |       11 |        0 | ... |
| Indiana Universit... |    61,060 |      0 |        False |        2 |        0 | ... |
| Instituto de Banc... |    20,876 |      0 |        False |        0 |        0 | ... |
| Iowa State Univer... |    29,611 |      0 |        False |        6 |        0 | ... |
| Ivy Tech Communit... |    42,092 |      0 |        False |        0 |        0 | ... |
| Johns Hopkins Uni... |   209,960 |      0 |        False |        0 |        0 | ... |
| Johnson County Co... |    21,020 |      0 |        False |        1 |        0 | ... |
| Kansas State Univ... |    47,726 |      0 |        False |        7 |        0 | ... |
| Kaplan University... |    56,606 |      0 |        False |        0 |        0 | ... |
| Kennesaw State Un... |    24,175 |      0 |        False |        2 |        0 | ... |
| Kent State Univer... |    27,855 |      0 |        False |        3 |        0 | ... |
| Lansing Community... |    41,280 |      0 |        False |        0 |        0 | ... |
| Liberty University   |    64,096 |      0 |        False |        4 |        0 | ... |
| Lone Star College... |   378,174 |      0 |        False |        0 |        1 | ... |
| Long Beach City C... |    51,564 |      0 |        False |        0 |        0 | ... |
| Los Angeles City ... |    21,028 |      0 |        False |        0 |        0 | ... |
| Los Angeles Pierc... |    20,506 |      0 |        False |        4 |        0 | ... |
| Louisiana State U... |    29,718 |      0 |        False |        2 |        0 | ... |
| Macomb Community ... |    47,938 |      0 |        False |        0 |        0 | ... |
| Mesa Community Co... |    77,085 |      0 |        False |        0 |        0 | ... |
| Metropolitan Stat... |    23,789 |      0 |        False |        1 |        0 | ... |
| Miami Dade College   |   509,888 |      0 |        False |        0 |        0 | ... |
| Michigan State Un... |   191,300 |      0 |        False |       15 |        0 | ... |
| Middle Tennessee ... |    26,442 |      0 |        False |        4 |        0 | ... |
| Mississippi State... |    40,848 |      0 |        False |        1 |        0 | ... |
| Missouri State Un... |    20,276 |      0 |        False |        0 |        0 | ... |
| Montgomery College   |    80,988 |      0 |        False |        4 |        0 | ... |
| Mt. San Antonio C... |    28,388 |      0 |        False |        1 |        0 | ... |
| Nassau Community ... |    23,550 |      0 |        False |        1 |        0 | ... |
| New York University  |   658,665 |      0 |        False |        1 |        0 | ... |
| North Carolina St... |    34,767 |      0 |        False |        7 |        0 | ... |
| Northeastern Univ... |    26,959 |      0 |        False |        6 |        0 | ... |
| Northern Arizona ... |    25,359 |      0 |        False |       13 |        0 | ... |
| Northern Illinois... |   114,950 |      0 |        False |        4 |        0 | ... |
| Northern Virginia... |   300,264 |      0 |        False |        2 |        0 | ... |
| Northwestern Univ... |   104,795 |      0 |        False |        3 |        0 | ... |
| Nova Southeastern... |    85,371 |      0 |        False |        2 |        1 | ... |
| Oakland Community... |   145,790 |      0 |        False |        2 |        0 | ... |
| Ohio State Univer... |    56,867 |      0 |        False |       28 |        0 | ... |
| Ohio University-M... |    26,201 |      0 |        False |        8 |        0 | ... |
| Oklahoma State Un... |    48,780 |      0 |        False |       11 |        0 | ... |
| Old Dominion Univ... |    24,753 |      0 |        False |        7 |        0 | ... |
| Orange Coast College |    22,654 |      0 |        False |        1 |        0 | ... |
| Oregon State Univ... |    24,962 |      0 |        False |        3 |        0 | ... |
| Palm Beach State ... |   117,416 |      0 |        False |        0 |        0 | ... |
| Palomar College      |    50,854 |      0 |        False |        1 |        0 | ... |
| Pasadena City Col... |    52,114 |      0 |        False |        2 |        0 | ... |
| Pennsylvania Stat... |    45,628 |      0 |        False |       24 |        0 | ... |
| Pima Community Co... |   443,628 |      0 |        False |        0 |        0 | ... |
| Portland Communit... |   277,056 |      0 |        False |        5 |        0 | ... |
| Portland State Un... |    28,584 |      0 |        False |        8 |        0 | ... |
| Purdue University... |   449,339 |      0 |        False |        7 |        0 | ... |
| Richland College     |    40,000 |      0 |        False |        0 |        0 | ... |
| Rio Salado College   |   251,090 |      0 |        False |        0 |        0 | ... |
| Rutgers Universit... |    39,950 |      0 |        False |       12 |        0 | ... |
| Sacramento City C... |    72,318 |      0 |        False |        1 |        0 | ... |
| Saddleback College   |    22,578 |      0 |        False |        1 |        0 | ... |
| Saint Louis Commu... |   175,200 |      0 |        False |        0 |        0 | ... |
| Salt Lake Communi... |   200,520 |      0 |        False |        1 |        0 | ... |
| San Antonio College  |    25,567 |      0 |        False |        1 |        0 | ... |
| San Diego Mesa Co... |    25,504 |      0 |        False |        0 |        0 | ... |
| San Diego State U... |    30,541 |      0 |        False |        6 |        0 | ... |
| San Francisco Sta... |    29,541 |      0 |        False |        4 |        0 | ... |
| San Jacinto Commu... |    88,176 |      0 |        False |        0 |        0 | ... |
| Santa Ana College    |    30,289 |      0 |        False |        0 |        0 | ... |
| Santa Monica College |    29,971 |      0 |        False |        0 |        0 | ... |
| Santa Rosa Junior... |    72,597 |      0 |        False |        0 |        0 | ... |
| Sinclair Communit... |   105,530 |      0 |        False |        0 |        0 | ... |
| South Texas College  |    29,604 |      0 |        False |        0 |        0 | ... |
| Southwestern College |    81,636 |      0 |        False |        0 |        0 | ... |
| St John's Univers... |   147,469 |      0 |        False |        5 |        0 | ... |
| St Petersburg Col... |   265,024 |      0 |        False |        0 |        1 | ... |
| Stony Brook Unive... |    23,920 |      0 |        False |       13 |        0 | ... |
| Suffolk County Co... |   107,148 |      0 |        False |        0 |        0 | ... |
| Syracuse University  |   145,803 |      0 |        False |       12 |        0 | ... |
| Tarrant County Co... |   300,372 |      0 |        False |        0 |        0 | ... |
| Temple University    |   294,840 |      0 |        False |        4 |        0 | ... |
| Texas A & M Unive... |   100,460 |      0 |        False |        3 |        0 | ... |
| Texas State Unive... |    68,174 |      0 |        False |        3 |        0 | ... |
| Texas Tech Univer... |   226,289 |      0 |        False |        3 |        0 | ... |
| The Community Col... |   157,626 |      0 |        False |        1 |        0 | ... |
| The University of... |    63,294 |      0 |        False |        3 |        0 | ... |
| The University of... |    90,582 |      0 |        False |        4 |        0 | ... |
| The University of... |   100,317 |      0 |        False |        2 |        0 | ... |
| The University of... |    51,112 |      0 |        False |        2 |        0 | ... |
| The University of... |    22,640 |      0 |        False |        5 |        0 | ... |
| The University of... |    61,936 |      0 |        False |        2 |        0 | ... |
| Thomas Edison Sta... |    20,251 |      0 |        False |        0 |        0 | ... |
| Tidewater Communi... |   224,707 |      0 |        False |        0 |        0 | ... |
| Towson University    |    21,464 |      0 |        False |        7 |        0 | ... |
| Troy University      |   209,376 |      0 |        False |        0 |        0 | ... |
| Tulsa Community C... |    80,616 |      0 |        False |        0 |        0 | ... |
| University at Buf... |    28,849 |      0 |        False |        3 |        0 | ... |
| University of Akr... |    54,940 |      0 |        False |        5 |        0 | ... |
| University of Ark... |    23,199 |      0 |        False |        5 |        0 | ... |
| University of Cal... |    72,274 |      0 |        False |       30 |        1 | ... |
| University of Cal... |    63,464 |      0 |        False |       24 |        0 | ... |
| University of Cal... |    54,378 |      0 |        False |        6 |        1 | ... |
| University of Cal... |    39,271 |      0 |        False |        8 |        0 | ... |
| University of Cal... |    20,900 |      0 |        False |        5 |        0 | ... |
| University of Cal... |    28,593 |      0 |        False |        6 |        0 | ... |
| University of Cal... |    21,685 |      0 |        False |        7 |        1 | ... |
| University of Cen... |   935,440 |      0 |        False |        6 |        0 | ... |
| University of Cin... |    66,658 |      0 |        False |        9 |        0 | ... |
| University of Col... |    32,558 |      0 |        False |        6 |        0 | ... |
| University of Col... |    44,990 |      0 |        False |        1 |        0 | ... |
| University of Con... |    51,736 |      0 |        False |        8 |        0 | ... |
| University of Del... |    64,467 |      0 |        False |        3 |        1 | ... |
| University of Flo... |    99,178 |      0 |        False |       10 |        0 | ... |
| University of Geo... |    34,816 |      0 |        False |        5 |        0 | ... |
| University of Haw... |    40,858 |      0 |        False |       12 |        0 | ... |
| University of Hou... |   119,460 |      0 |        False |        6 |        0 | ... |
| University of Ill... |    88,814 |      0 |        False |        5 |        0 | ... |
| University of Iowa   |   119,240 |      0 |        False |       10 |        0 | ... |
| University of Kansas |   111,756 |      0 |        False |        4 |        0 | ... |
| University of Ken... |   163,356 |      0 |        False |        5 |        0 | ... |
| University of Lou... |    63,456 |      0 |        False |        0 |        0 | ... |
| University of Mar... |    75,262 |      0 |        False |        4 |        0 | ... |
| University of Mar... |   256,278 |      0 |        False |        0 |        0 | ... |
| University of Mas... |    28,084 |      0 |        False |       13 |        0 | ... |
| University of Mem... |    90,900 |      0 |        False |        2 |        0 | ... |
| University of Mic... |    42,716 |      0 |        False |       14 |        0 | ... |
| University of Min... |   105,114 |      0 |        False |       12 |        0 | ... |
| University of Mis... |    33,762 |      0 |        False |       11 |        0 | ... |
| University of Neb... |    24,593 |      0 |        False |        3 |        0 | ... |
| University of Nev... |    54,728 |      0 |        False |        1 |        0 | ... |
| University of New... |    28,977 |      0 |        False |        2 |        0 | ... |
| University of Nor... |    29,137 |      0 |        False |       12 |        0 | ... |
| University of Nor... |    25,277 |      0 |        False |        2 |        0 | ... |
| University of Nor... |    75,636 |      0 |        False |        2 |        0 | ... |
| University of Okl... |    27,138 |      0 |        False |       13 |        0 | ... |
| University of Oregon |    73,188 |      0 |        False |        8 |        0 | ... |
| University of Pen... |   148,992 |      0 |        False |       12 |        0 | ... |
| University of Pit... |    28,766 |      0 |        False |        4 |        0 | ... |
| University of Sou... |    30,721 |      0 |        False |        1 |        0 | ... |
| University of Sou... |    39,596 |      0 |        False |        1 |        0 | ... |
| University of Sou... |   342,090 |      0 |        False |        8 |        0 | ... |
| University of Toledo |    67,830 |      0 |        False |        2 |        0 | ... |
| University of Utah   |    31,660 |      0 |        False |        5 |        0 | ... |
| University of Vir... |   145,782 |      0 |        False |       13 |        0 | ... |
| University of Was... |    42,444 |      0 |        False |        5 |        0 | ... |
| University of Wis... |    41,946 |      0 |        False |       24 |        0 | ... |
| University of Wis... |    29,350 |      0 |        False |        3 |        0 | ... |
| Utah State Univer... |    26,757 |      0 |        False |        3 |        0 | ... |
| Utah Valley Unive... |    33,395 |      0 |        False |        3 |        0 | ... |
| Valencia College     |   341,048 |      0 |        False |        0 |        0 | ... |
| Virginia Commonwe... |    94,881 |      0 |        False |        6 |        0 | ... |
| Walden University    |    48,982 |      0 |        False |        0 |        0 | ... |
| Washington State ... |   109,316 |      0 |        False |        8 |        0 | ... |

Even though San Jose State University, the University of Arizona, the University of Illinois and Virginia Polytech do not have the higest enrollment numbers, they are the only ones to report murders. Could do further analysis to figure out what makes these schools unique.

In [32]:
forcible_outliers = crime_analysis.order_by('forcible', reverse=True)

In [33]:
forcible_outliers.print_table(max_rows=None)

| instname             | total_enr | murder | manslaughter | forcible | nonforce | ... |
| -------------------- | --------- | ------ | ------------ | -------- | -------- | --- |
| University of Cal... |    72,274 |      0 |        False |       30 |        1 | ... |
| Ohio State Univer... |    56,867 |      0 |        False |       28 |        0 | ... |
| Pennsylvania Stat... |    45,628 |      0 |        False |       24 |        0 | ... |
| University of Cal... |    63,464 |      0 |        False |       24 |        0 | ... |
| University of Wis... |    41,946 |      0 |        False |       24 |        0 | ... |
| Harvard University   |    54,784 |      0 |        False |       21 |        0 | ... |
| Arizona State Uni... |   289,016 |      0 |        False |       17 |        1 | ... |
| George Washington... |   202,080 |      0 |        False |       16 |        0 | ... |
| Michigan State Un... |   191,300 |      0 |        False |       15 |        0 | ... |
| University of Mic... |    42,716 |      0 |        False |       14 |        0 | ... |
| Virginia Polytech... |   371,232 |      1 |        False |       14 |        0 | ... |
| Northern Arizona ... |    25,359 |      0 |        False |       13 |        0 | ... |
| Stony Brook Unive... |    23,920 |      0 |        False |       13 |        0 | ... |
| University of Mas... |    28,084 |      0 |        False |       13 |        0 | ... |
| University of Okl... |    27,138 |      0 |        False |       13 |        0 | ... |
| University of Vir... |   145,782 |      0 |        False |       13 |        0 | ... |
| Rutgers Universit... |    39,950 |      0 |        False |       12 |        0 | ... |
| Syracuse University  |   145,803 |      0 |        False |       12 |        0 | ... |
| University of Haw... |    40,858 |      0 |        False |       12 |        0 | ... |
| University of Min... |   105,114 |      0 |        False |       12 |        0 | ... |
| University of Nor... |    29,137 |      0 |        False |       12 |        0 | ... |
| University of Pen... |   148,992 |      0 |        False |       12 |        0 | ... |
| Indiana Universit... |    42,731 |      0 |        False |       11 |        0 | ... |
| Oklahoma State Un... |    48,780 |      0 |        False |       11 |        0 | ... |
| University of Mis... |    33,762 |      0 |        False |       11 |        0 | ... |
| University of Flo... |    99,178 |      0 |        False |       10 |        0 | ... |
| University of Iowa   |   119,240 |      0 |        False |       10 |        0 | ... |
| East Carolina Uni... |    54,772 |      0 |        False |        9 |        0 | ... |
| University of Cin... |    66,658 |      0 |        False |        9 |        0 | ... |
| University of Ill... |    84,273 |      1 |        False |        9 |        0 | ... |
| Ball State Univer... |    44,294 |      0 |        False |        8 |        0 | ... |
| George Mason Univ... |    33,320 |      0 |        False |        8 |        0 | ... |
| Ohio University-M... |    26,201 |      0 |        False |        8 |        0 | ... |
| Portland State Un... |    28,584 |      0 |        False |        8 |        0 | ... |
| University of Cal... |    39,271 |      0 |        False |        8 |        0 | ... |
| University of Con... |    51,736 |      0 |        False |        8 |        0 | ... |
| University of Oregon |    73,188 |      0 |        False |        8 |        0 | ... |
| University of Sou... |   342,090 |      0 |        False |        8 |        0 | ... |
| Washington State ... |   109,316 |      0 |        False |        8 |        0 | ... |
| California State ... |    21,107 |      0 |        False |        7 |        0 | ... |
| Cornell University   |    21,131 |      0 |        False |        7 |        0 | ... |
| Kansas State Univ... |    47,726 |      0 |        False |        7 |        0 | ... |
| North Carolina St... |    34,767 |      0 |        False |        7 |        0 | ... |
| Old Dominion Univ... |    24,753 |      0 |        False |        7 |        0 | ... |
| Purdue University... |   449,339 |      0 |        False |        7 |        0 | ... |
| Towson University    |    21,464 |      0 |        False |        7 |        0 | ... |
| University of Cal... |    21,685 |      0 |        False |        7 |        1 | ... |
| Boston University    |    64,878 |      0 |        False |        6 |        0 | ... |
| Iowa State Univer... |    29,611 |      0 |        False |        6 |        0 | ... |
| Northeastern Univ... |    26,959 |      0 |        False |        6 |        0 | ... |
| San Diego State U... |    30,541 |      0 |        False |        6 |        0 | ... |
| University of Cal... |    54,378 |      0 |        False |        6 |        1 | ... |
| University of Cal... |    28,593 |      0 |        False |        6 |        0 | ... |
| University of Cen... |   935,440 |      0 |        False |        6 |        0 | ... |
| University of Col... |    32,558 |      0 |        False |        6 |        0 | ... |
| University of Hou... |   119,460 |      0 |        False |        6 |        0 | ... |
| Virginia Commonwe... |    94,881 |      0 |        False |        6 |        0 | ... |
| Central Michigan ... |    28,194 |      0 |        False |        5 |        0 | ... |
| Drexel University    |   149,160 |      0 |        False |        5 |        0 | ... |
| Georgia Institute... |    41,882 |      0 |        False |        5 |        0 | ... |
| Portland Communit... |   277,056 |      0 |        False |        5 |        0 | ... |
| St John's Univers... |   147,469 |      0 |        False |        5 |        0 | ... |
| The University of... |    22,640 |      0 |        False |        5 |        0 | ... |
| University of Akr... |    54,940 |      0 |        False |        5 |        0 | ... |
| University of Ark... |    23,199 |      0 |        False |        5 |        0 | ... |
| University of Cal... |    20,900 |      0 |        False |        5 |        0 | ... |
| University of Geo... |    34,816 |      0 |        False |        5 |        0 | ... |
| University of Ill... |    88,814 |      0 |        False |        5 |        0 | ... |
| University of Ken... |   163,356 |      0 |        False |        5 |        0 | ... |
| University of Utah   |    31,660 |      0 |        False |        5 |        0 | ... |
| University of Was... |    42,444 |      0 |        False |        5 |        0 | ... |
| Western Kentucky ... |   126,216 |      0 |        False |        5 |        0 | ... |
| Colorado State Un... |    30,467 |      0 |        False |        4 |        0 | ... |
| Columbia Universi... |   104,200 |      0 |        False |        4 |        0 | ... |
| Eastern Michigan ... |   210,771 |      0 |        False |        4 |        0 | ... |
| Georgia State Uni... |    64,044 |      0 |        False |        4 |        0 | ... |
| Liberty University   |    64,096 |      0 |        False |        4 |        0 | ... |
| Los Angeles Pierc... |    20,506 |      0 |        False |        4 |        0 | ... |
| Middle Tennessee ... |    26,442 |      0 |        False |        4 |        0 | ... |
| Montgomery College   |    80,988 |      0 |        False |        4 |        0 | ... |
| Northern Illinois... |   114,950 |      0 |        False |        4 |        0 | ... |
| San Francisco Sta... |    29,541 |      0 |        False |        4 |        0 | ... |
| Temple University    |   294,840 |      0 |        False |        4 |        0 | ... |
| The University of... |    90,582 |      0 |        False |        4 |        0 | ... |
| University of Kansas |   111,756 |      0 |        False |        4 |        0 | ... |
| University of Mar... |    75,262 |      0 |        False |        4 |        0 | ... |
| University of Pit... |    28,766 |      0 |        False |        4 |        0 | ... |
| West Virginia Uni... |    29,617 |      0 |        False |        4 |        0 | ... |
| California State ... |    34,870 |      0 |        False |        3 |        0 | ... |
| Central New Mexic... |   166,062 |      0 |        False |        3 |        0 | ... |
| Cuyahoga Communit... |   215,971 |      0 |        False |        3 |        0 | ... |
| Florida Internati... |    44,616 |      0 |        False |        3 |        0 | ... |
| Georgia Southern ... |    20,212 |      0 |        False |        3 |        0 | ... |
| Kent State Univer... |    27,855 |      0 |        False |        3 |        0 | ... |
| Northwestern Univ... |   104,795 |      0 |        False |        3 |        0 | ... |
| Oregon State Univ... |    24,962 |      0 |        False |        3 |        0 | ... |
| San Jose State Un... |    60,472 |      2 |        False |        3 |        0 | ... |
| Texas A & M Unive... |   100,460 |      0 |        False |        3 |        0 | ... |
| Texas State Unive... |    68,174 |      0 |        False |        3 |        0 | ... |
| Texas Tech Univer... |   226,289 |      0 |        False |        3 |        0 | ... |
| The University of... |    63,294 |      0 |        False |        3 |        0 | ... |
| University at Buf... |    28,849 |      0 |        False |        3 |        0 | ... |
| University of Ari... |    39,236 |      1 |        False |        3 |        0 | ... |
| University of Del... |    64,467 |      0 |        False |        3 |        1 | ... |
| University of Neb... |    24,593 |      0 |        False |        3 |        0 | ... |
| University of Wis... |    29,350 |      0 |        False |        3 |        0 | ... |
| Utah State Univer... |    26,757 |      0 |        False |        3 |        0 | ... |
| Utah Valley Unive... |    33,395 |      0 |        False |        3 |        0 | ... |
| Western Michigan ... |   250,860 |      0 |        False |        3 |        1 | ... |
| Ashford University   |    74,596 |      0 |        False |        2 |        0 | ... |
| California State ... |    28,016 |      0 |        False |        2 |        0 | ... |
| College of Southe... |   113,151 |      0 |        False |        2 |        0 | ... |
| CUNY Borough of M... |    24,463 |      0 |        False |        2 |        0 | ... |
| Florida State Uni... |    41,087 |      0 |         True |        2 |        0 | ... |
| Grand Valley Stat... |   123,310 |      0 |        False |        2 |        0 | ... |
| Illinois State Un... |    21,310 |      0 |        False |        2 |        0 | ... |
| Indiana Universit... |    61,060 |      0 |        False |        2 |        0 | ... |
| Kennesaw State Un... |    24,175 |      0 |        False |        2 |        0 | ... |
| Louisiana State U... |    29,718 |      0 |        False |        2 |        0 | ... |
| Northern Virginia... |   300,264 |      0 |        False |        2 |        0 | ... |
| Nova Southeastern... |    85,371 |      0 |        False |        2 |        1 | ... |
| Oakland Community... |   145,790 |      0 |        False |        2 |        0 | ... |
| Pasadena City Col... |    52,114 |      0 |        False |        2 |        0 | ... |
| The University of... |   100,317 |      0 |        False |        2 |        0 | ... |
| The University of... |    51,112 |      0 |        False |        2 |        0 | ... |
| The University of... |    61,936 |      0 |        False |        2 |        0 | ... |
| University of Mem... |    90,900 |      0 |        False |        2 |        0 | ... |
| University of New... |    28,977 |      0 |        False |        2 |        0 | ... |
| University of Nor... |    25,277 |      0 |        False |        2 |        0 | ... |
| University of Nor... |    75,636 |      0 |        False |        2 |        0 | ... |
| University of Toledo |    67,830 |      0 |        False |        2 |        0 | ... |
| Wayne State Unive... |   123,060 |      0 |        False |        2 |        0 | ... |
| Weber State Unive... |    25,301 |      0 |        False |        2 |        0 | ... |
| American River Co... |    95,250 |      0 |        False |        1 |        2 | ... |
| Auburn University    |    25,469 |      0 |        False |        1 |        0 | ... |
| California State ... |    21,981 |      0 |        False |        1 |        0 | ... |
| California State ... |    21,284 |      0 |        False |        1 |        0 | ... |
| California State ... |    36,911 |      0 |        False |        1 |        0 | ... |
| Cerritos College     |    21,335 |      0 |        False |        1 |        0 | ... |
| City College of S... |    34,558 |      0 |        False |        1 |        0 | ... |
| DePaul University    |   152,388 |      0 |        False |        1 |        0 | ... |
| Florida Atlantic ... |   233,968 |      0 |        False |        1 |        0 | ... |
| Grand Canyon Univ... |    40,487 |      0 |        False |        1 |        0 | ... |
| Harrisburg Area C... |   112,975 |      0 |        False |        1 |        0 | ... |
| Johnson County Co... |    21,020 |      0 |        False |        1 |        0 | ... |
| Metropolitan Stat... |    23,789 |      0 |        False |        1 |        0 | ... |
| Mississippi State... |    40,848 |      0 |        False |        1 |        0 | ... |
| Mt. San Antonio C... |    28,388 |      0 |        False |        1 |        0 | ... |
| Nassau Community ... |    23,550 |      0 |        False |        1 |        0 | ... |
| New York University  |   658,665 |      0 |        False |        1 |        0 | ... |
| Orange Coast College |    22,654 |      0 |        False |        1 |        0 | ... |
| Palomar College      |    50,854 |      0 |        False |        1 |        0 | ... |
| Sacramento City C... |    72,318 |      0 |        False |        1 |        0 | ... |
| Saddleback College   |    22,578 |      0 |        False |        1 |        0 | ... |
| Salt Lake Communi... |   200,520 |      0 |        False |        1 |        0 | ... |
| San Antonio College  |    25,567 |      0 |        False |        1 |        0 | ... |
| The Community Col... |   157,626 |      0 |        False |        1 |        0 | ... |
| University of Col... |    44,990 |      0 |        False |        1 |        0 | ... |
| University of Nev... |    54,728 |      0 |        False |        1 |        0 | ... |
| University of Sou... |    30,721 |      0 |        False |        1 |        0 | ... |
| University of Sou... |    39,596 |      0 |        False |        1 |        0 | ... |
| Wayne County Comm... |   122,640 |      0 |        False |        1 |        0 | ... |
| Austin Community ... | 1,082,400 |      0 |        False |        0 |        0 | ... |
| Brigham Young Uni... |   170,505 |      0 |        False |        0 |        0 | ... |
| Broward College      |   379,782 |      0 |        False |        0 |        0 | ... |
| California State ... |   144,624 |      0 |        False |        0 |        0 | ... |
| Capella University   |    36,375 |      0 |        False |        0 |        0 | ... |
| Central Texas Col... |    80,985 |      0 |        False |        0 |        0 | ... |
| College of DuPage    |   157,254 |      0 |        False |        0 |        0 | ... |
| Collin County Com... |    82,779 |      0 |        False |        0 |        0 | ... |
| Columbus State Co... |   247,368 |      0 |        False |        0 |        0 | ... |
| Community College... |    81,720 |      0 |        False |        0 |        0 | ... |
| CUNY Hunter College  |   136,932 |      0 |        False |        0 |        0 | ... |
| CUNY Queens College  |    20,993 |      0 |        False |        0 |        0 | ... |
| De Anza College      |    24,187 |      0 |        False |        0 |        0 | ... |
| Delgado Community... |   163,488 |      0 |        False |        0 |        0 | ... |
| Des Moines Area C... |   279,675 |      0 |        False |        0 |        0 | ... |
| DeVry University-... |   279,210 |      0 |        False |        0 |        0 | ... |
| Diablo Valley Col... |    20,310 |      0 |        False |        0 |        0 | ... |
| East Los Angeles ... |    37,057 |      0 |        False |        0 |        0 | ... |
| El Camino Communi... |    24,463 |      0 |        False |        0 |        0 | ... |
| El Paso Community... |   215,061 |      0 |        False |        0 |        0 | ... |
| Everest Universit... |    25,537 |      0 |        False |        0 |        0 | ... |
| Excelsior College    |    35,608 |      0 |        False |        0 |        0 | ... |
| Florida State Col... |   246,904 |      0 |        False |        0 |        0 | ... |
| Fresno City College  |    40,270 |      0 |        False |        0 |        0 | ... |
| Front Range Commu... |    82,272 |      0 |        False |        0 |        0 | ... |
| Full Sail University |    20,160 |      0 |        False |        0 |        0 | ... |
| Georgia Perimeter... |   134,980 |      0 |        False |        0 |        0 | ... |
| Glendale Communit... |    42,752 |      0 |        False |        0 |        0 | ... |
| Hillsborough Comm... |   141,645 |      0 |        False |        0 |        0 | ... |
| Houston Community... | 1,323,315 |      0 |        False |        0 |        0 | ... |
| Instituto de Banc... |    20,876 |      0 |        False |        0 |        0 | ... |
| Ivy Tech Communit... |    42,092 |      0 |        False |        0 |        0 | ... |
| Johns Hopkins Uni... |   209,960 |      0 |        False |        0 |        0 | ... |
| Kaplan University... |    56,606 |      0 |        False |        0 |        0 | ... |
| Lansing Community... |    41,280 |      0 |        False |        0 |        0 | ... |
| Lone Star College... |   378,174 |      0 |        False |        0 |        1 | ... |
| Long Beach City C... |    51,564 |      0 |        False |        0 |        0 | ... |
| Los Angeles City ... |    21,028 |      0 |        False |        0 |        0 | ... |
| Macomb Community ... |    47,938 |      0 |        False |        0 |        0 | ... |
| Mesa Community Co... |    77,085 |      0 |        False |        0 |        0 | ... |
| Miami Dade College   |   509,888 |      0 |        False |        0 |        0 | ... |
| Missouri State Un... |    20,276 |      0 |        False |        0 |        0 | ... |
| Palm Beach State ... |   117,416 |      0 |        False |        0 |        0 | ... |
| Pima Community Co... |   443,628 |      0 |        False |        0 |        0 | ... |
| Richland College     |    40,000 |      0 |        False |        0 |        0 | ... |
| Rio Salado College   |   251,090 |      0 |        False |        0 |        0 | ... |
| Saint Louis Commu... |   175,200 |      0 |        False |        0 |        0 | ... |
| San Diego Mesa Co... |    25,504 |      0 |        False |        0 |        0 | ... |
| San Jacinto Commu... |    88,176 |      0 |        False |        0 |        0 | ... |
| Santa Ana College    |    30,289 |      0 |        False |        0 |        0 | ... |
| Santa Monica College |    29,971 |      0 |        False |        0 |        0 | ... |
| Santa Rosa Junior... |    72,597 |      0 |        False |        0 |        0 | ... |
| Sinclair Communit... |   105,530 |      0 |        False |        0 |        0 | ... |
| South Texas College  |    29,604 |      0 |        False |        0 |        0 | ... |
| Southwestern College |    81,636 |      0 |        False |        0 |        0 | ... |
| St Petersburg Col... |   265,024 |      0 |        False |        0 |        1 | ... |
| Suffolk County Co... |   107,148 |      0 |        False |        0 |        0 | ... |
| Tarrant County Co... |   300,372 |      0 |        False |        0 |        0 | ... |
| Thomas Edison Sta... |    20,251 |      0 |        False |        0 |        0 | ... |
| Tidewater Communi... |   224,707 |      0 |        False |        0 |        0 | ... |

In [55]:
arson_outliers = crime_analysis.order_by('arson', reverse = True).exclude('manslaughter').exclude('nonforce').exclude('murder').exclude('forcible').exclude('total_enr')

In [56]:
arson_outliers.print_table(max_rows=None)

| instname             | robbery | agg_aslt | burglary | vehicle | arson |
| -------------------- | ------- | -------- | -------- | ------- | ----- |
| Arizona State Uni... |      11 |       27 |       90 |      17 |    11 |
| Pennsylvania Stat... |       2 |        6 |      112 |       1 |    11 |
| Eastern Michigan ... |       2 |        1 |       13 |       2 |     7 |
| Fresno City College  |       1 |        2 |       33 |      10 |     7 |
| St John's Univers... |       1 |        0 |       15 |       1 |     7 |
| Ohio State Univer... |       7 |        0 |       22 |       8 |     6 |
| Ohio University-M... |       1 |        1 |       21 |       2 |     6 |
| University of Cal... |       9 |        7 |       40 |      14 |     6 |
| California State ... |       3 |        0 |       12 |       4 |     5 |
| Brigham Young Uni... |       0 |        1 |       10 |       3 |     4 |
| San Jose State Un... |       2 |       13 |       24 |      13 |     4 |
| University of Cal... |       0 |        6 |       29 |      18 |     4 |
| University of Ill... |       4 |        4 |       30 |       5 |     4 |
| University of Mic... |       4 |        8 |       37 |      12 |     4 |
| University of Toledo |       1 |        4 |      118 |       0 |     4 |
| Colorado State Un... |       1 |        0 |       16 |       1 |     3 |
| Florida Atlantic ... |       1 |        0 |       22 |      13 |     3 |
| Indiana Universit... |       3 |       12 |       89 |      18 |     3 |
| Iowa State Univer... |       1 |        8 |       47 |       2 |     3 |
| Louisiana State U... |       9 |        9 |       47 |      10 |     3 |
| Rutgers Universit... |       0 |        5 |       65 |       7 |     3 |
| The University of... |       0 |        6 |       51 |       2 |     3 |
| University of Cal... |       1 |        3 |       40 |       4 |     3 |
| University of Con... |       3 |        3 |       54 |       0 |     3 |
| University of Geo... |       1 |        2 |       53 |       5 |     3 |
| Cornell University   |       0 |        0 |       13 |       0 |     2 |
| El Camino Communi... |       1 |        2 |        2 |      13 |     2 |
| Liberty University   |       2 |        1 |        5 |       1 |     2 |
| Northern Illinois... |       0 |        1 |       22 |       0 |     2 |
| Purdue University... |       1 |        2 |       49 |       4 |     2 |
| Santa Rosa Junior... |       1 |        1 |        1 |       0 |     2 |
| Stony Brook Unive... |       2 |        2 |       96 |       7 |     2 |
| University of Ari... |       0 |        0 |       43 |       6 |     2 |
| University of Okl... |       0 |        1 |       29 |      10 |     2 |
| University of Sou... |       5 |        1 |       50 |       4 |     2 |
| Wayne State Unive... |       3 |        2 |       18 |       8 |     2 |
| Western Michigan ... |       0 |        2 |       13 |       1 |     2 |
| California State ... |       0 |        7 |       29 |      19 |     1 |
| Central Michigan ... |       1 |        2 |       15 |       1 |     1 |
| College of DuPage    |       2 |        0 |        5 |       0 |     1 |
| Columbia Universi... |       1 |        4 |       25 |       0 |     1 |
| CUNY Hunter College  |       2 |        0 |        7 |       0 |     1 |
| Florida State Uni... |       8 |        8 |       67 |      10 |     1 |
| George Washington... |       1 |        4 |       45 |       2 |     1 |
| Grand Valley Stat... |       0 |        0 |        6 |       0 |     1 |
| Illinois State Un... |       1 |       21 |       26 |       2 |     1 |
| Indiana Universit... |       3 |        7 |       51 |      10 |     1 |
| Kent State Univer... |       1 |        1 |       17 |       1 |     1 |
| Mississippi State... |       0 |        1 |       56 |       2 |     1 |
| Northern Arizona ... |       3 |        5 |       35 |       2 |     1 |
| Oregon State Univ... |       1 |        3 |       36 |      28 |     1 |
| Pasadena City Col... |       2 |        0 |        2 |       8 |     1 |
| Portland State Un... |       1 |        0 |       41 |       3 |     1 |
| Richland College     |       0 |        1 |        0 |       2 |     1 |
| Saddleback College   |       0 |        6 |        3 |       0 |     1 |
| Saint Louis Commu... |       0 |        0 |        2 |       5 |     1 |
| San Francisco Sta... |       2 |        0 |       41 |       8 |     1 |
| Syracuse University  |       0 |        4 |       36 |       0 |     1 |
| Texas A & M Unive... |       1 |        0 |       29 |       3 |     1 |
| Texas State Unive... |       1 |        5 |       44 |       3 |     1 |
| Texas Tech Univer... |       1 |        3 |       21 |       6 |     1 |
| The Community Col... |       7 |        0 |        0 |       1 |     1 |
| The University of... |       5 |        3 |       68 |       2 |     1 |
| University at Buf... |       3 |        4 |       73 |       6 |     1 |
| University of Cal... |       5 |        4 |       86 |      13 |     1 |
| University of Cal... |       2 |        1 |       52 |       5 |     1 |
| University of Cal... |       4 |        1 |       32 |      23 |     1 |
| University of Cin... |       5 |        4 |       15 |       7 |     1 |
| University of Col... |       5 |        8 |       42 |      10 |     1 |
| University of Del... |       4 |        3 |       26 |       1 |     1 |
| University of Kansas |       1 |        9 |       39 |       7 |     1 |
| University of Mar... |       4 |        4 |       64 |      37 |     1 |
| University of Mis... |       1 |        8 |       10 |       1 |     1 |
| University of Neb... |       0 |        1 |        7 |       3 |     1 |
| University of Nev... |       5 |        1 |       23 |      34 |     1 |
| University of Nor... |       3 |        3 |       36 |       3 |     1 |
| University of Pen... |       9 |        2 |       19 |       1 |     1 |
| University of Wis... |       2 |        3 |       32 |       3 |     1 |
| University of Wis... |       0 |        0 |       39 |       0 |     1 |
| West Virginia Uni... |       1 |        7 |       22 |       4 |     1 |
| American River Co... |       3 |        2 |        6 |       8 |     0 |
| Ashford University   |       0 |        0 |        1 |       0 |     0 |
| Auburn University    |       2 |        0 |       22 |       3 |     0 |
| Austin Community ... |       0 |        1 |        2 |       0 |     0 |
| Ball State Univer... |       1 |        0 |       31 |       0 |     0 |
| Boston University    |       2 |        3 |       60 |       2 |     0 |
| Broward College      |       3 |        2 |        6 |      10 |     0 |
| California State ... |       2 |        0 |       23 |      15 |     0 |
| California State ... |       1 |        7 |        6 |      14 |     0 |
| California State ... |       3 |        1 |       24 |       5 |     0 |
| California State ... |       3 |        2 |        5 |      24 |     0 |
| California State ... |       5 |        6 |       34 |      15 |     0 |
| Capella University   |       0 |        0 |        0 |       0 |     0 |
| Central New Mexic... |       0 |        9 |        3 |       4 |     0 |
| Central Texas Col... |       0 |        1 |        0 |       0 |     0 |
| Cerritos College     |       1 |        1 |        3 |      16 |     0 |
| City College of S... |       4 |        1 |        7 |       4 |     0 |
| College of Southe... |       2 |        0 |        1 |       3 |     0 |
| Collin County Com... |       0 |        0 |        4 |       0 |     0 |
| Columbus State Co... |       0 |        0 |        1 |       0 |     0 |
| Community College... |       1 |        0 |        2 |       1 |     0 |
| CUNY Borough of M... |       0 |        2 |        2 |       0 |     0 |
| CUNY Queens College  |       0 |        0 |       16 |       0 |     0 |
| Cuyahoga Communit... |       3 |        0 |        2 |       7 |     0 |
| De Anza College      |       0 |        0 |        9 |       2 |     0 |
| Delgado Community... |       0 |        4 |       12 |       3 |     0 |
| DePaul University    |       0 |        0 |       15 |       0 |     0 |
| Des Moines Area C... |       0 |        1 |        1 |       0 |     0 |
| DeVry University-... |       0 |        0 |        0 |       0 |     0 |
| Diablo Valley Col... |       1 |        1 |        1 |       4 |     0 |
| Drexel University    |       0 |        0 |       50 |       0 |     0 |
| East Carolina Uni... |       4 |        2 |       17 |       2 |     0 |
| East Los Angeles ... |       1 |        1 |        7 |      12 |     0 |
| El Paso Community... |       0 |        0 |        3 |      19 |     0 |
| Everest Universit... |       0 |        0 |        0 |       2 |     0 |
| Excelsior College    |       0 |        0 |        0 |       0 |     0 |
| Florida Internati... |       3 |        4 |       42 |      17 |     0 |
| Florida State Col... |       1 |        2 |        1 |       1 |     0 |
| Front Range Commu... |       0 |        0 |        0 |       3 |     0 |
| Full Sail University |       2 |        2 |        0 |       3 |     0 |
| George Mason Univ... |       0 |        0 |       31 |       0 |     0 |
| Georgia Institute... |       5 |        3 |       18 |      15 |     0 |
| Georgia Perimeter... |       2 |        0 |        0 |       4 |     0 |
| Georgia Southern ... |       2 |        0 |       10 |       0 |     0 |
| Georgia State Uni... |       4 |        2 |        8 |       2 |     0 |
| Glendale Communit... |       0 |        1 |        2 |      10 |     0 |
| Grand Canyon Univ... |       0 |        0 |       10 |       0 |     0 |
| Harrisburg Area C... |       1 |        2 |        2 |       1 |     0 |
| Harvard University   |       1 |        7 |       28 |       3 |     0 |
| Hillsborough Comm... |       0 |        0 |        4 |       1 |     0 |
| Houston Community... |       1 |        6 |       36 |      14 |     0 |
| Instituto de Banc... |      19 |        1 |        4 |       0 |     0 |
| Ivy Tech Communit... |       0 |        0 |        1 |       0 |     0 |
| Johns Hopkins Uni... |       0 |        0 |        1 |       2 |     0 |
| Johnson County Co... |       0 |        1 |       14 |       3 |     0 |
| Kansas State Univ... |       0 |        2 |       22 |       2 |     0 |
| Kaplan University... |       0 |        0 |        0 |       0 |     0 |
| Kennesaw State Un... |       0 |        0 |       34 |       3 |     0 |
| Lansing Community... |       0 |        1 |       60 |       0 |     0 |
| Lone Star College... |       1 |        1 |        1 |       1 |     0 |
| Long Beach City C... |       1 |        1 |       13 |      19 |     0 |
| Los Angeles City ... |       1 |        0 |        3 |       0 |     0 |
| Los Angeles Pierc... |       4 |        0 |        1 |       1 |     0 |
| Macomb Community ... |       0 |        0 |        0 |       3 |     0 |
| Mesa Community Co... |       0 |        4 |        1 |       0 |     0 |
| Metropolitan Stat... |       0 |        2 |       66 |       7 |     0 |
| Miami Dade College   |       5 |        2 |        0 |      36 |     0 |
| Michigan State Un... |       1 |       10 |       77 |       9 |     0 |
| Middle Tennessee ... |       2 |        5 |       30 |       5 |     0 |
| Missouri State Un... |       0 |        0 |        3 |       6 |     0 |
| Montgomery College   |       1 |        2 |        3 |       5 |     0 |
| Mt. San Antonio C... |       0 |        3 |        6 |       5 |     0 |
| Nassau Community ... |       0 |        0 |        5 |      13 |     0 |
| New York University  |       0 |        0 |       35 |       0 |     0 |
| North Carolina St... |       6 |        9 |       41 |      12 |     0 |
| Northeastern Univ... |       3 |        5 |       17 |       0 |     0 |
| Northern Virginia... |       3 |        2 |        1 |       0 |     0 |
| Northwestern Univ... |       3 |        0 |       57 |       5 |     0 |
| Nova Southeastern... |       0 |        0 |        5 |       1 |     0 |
| Oakland Community... |       0 |        0 |        3 |       5 |     0 |
| Oklahoma State Un... |       0 |        1 |       45 |       1 |     0 |
| Old Dominion Univ... |       6 |        2 |       34 |       6 |     0 |
| Orange Coast College |       0 |        0 |        7 |       1 |     0 |
| Palm Beach State ... |       0 |        0 |        0 |       3 |     0 |
| Palomar College      |       0 |        2 |        0 |       0 |     0 |
| Pima Community Co... |       3 |        2 |        4 |      16 |     0 |
| Portland Communit... |       2 |        6 |        5 |       3 |     0 |
| Rio Salado College   |       0 |        0 |        0 |       0 |     0 |
| Sacramento City C... |       1 |        0 |        1 |      12 |     0 |
| Salt Lake Communi... |       1 |        0 |        9 |       2 |     0 |
| San Antonio College  |       1 |        2 |        0 |      11 |     0 |
| San Diego Mesa Co... |       0 |        0 |        1 |       8 |     0 |
| San Diego State U... |       2 |        4 |       42 |      39 |     0 |
| San Jacinto Commu... |       0 |        0 |        6 |       4 |     0 |
| Santa Ana College    |       2 |        1 |        3 |       3 |     0 |
| Santa Monica College |       2 |        0 |        8 |       1 |     0 |
| Sinclair Communit... |       0 |        0 |        2 |       0 |     0 |
| South Texas College  |       0 |        2 |        0 |       0 |     0 |
| Southwestern College |       0 |        0 |        0 |       6 |     0 |
| St Petersburg Col... |       0 |        0 |        0 |       1 |     0 |
| Suffolk County Co... |       0 |        0 |        0 |       0 |     0 |
| Tarrant County Co... |       0 |        1 |        1 |       8 |     0 |
| Temple University    |       4 |        4 |        5 |       0 |     0 |
| The University of... |       1 |        0 |       30 |      10 |     0 |
| The University of... |       2 |        2 |       36 |       7 |     0 |
| The University of... |       1 |        3 |       28 |      21 |     0 |
| The University of... |       3 |        6 |       13 |       5 |     0 |
| Thomas Edison Sta... |       0 |        0 |        0 |       0 |     0 |
| Tidewater Communi... |       0 |        0 |        7 |       3 |     0 |
| Towson University    |       2 |        3 |       11 |       0 |     0 |
| Troy University      |       0 |        0 |        8 |       2 |     0 |
| Tulsa Community C... |       0 |        0 |       29 |       4 |     0 |
| University of Akr... |       4 |        1 |        5 |      13 |     0 |
| University of Ark... |       1 |        2 |       46 |      16 |     0 |
| University of Cal... |       2 |        4 |      118 |       7 |     0 |
| University of Cen... |      10 |       12 |       32 |      35 |     0 |
| University of Col... |       0 |        2 |       75 |      11 |     0 |
| University of Flo... |       1 |        6 |       27 |      14 |     0 |
| University of Haw... |       2 |       16 |       64 |      16 |     0 |
| University of Hou... |       1 |        3 |       74 |      22 |     0 |
| University of Ill... |       6 |        8 |       14 |       0 |     0 |
| University of Iowa   |       0 |        6 |       20 |       2 |     0 |
| University of Ken... |       3 |        4 |       13 |      12 |     0 |
| University of Lou... |       0 |        0 |       10 |       0 |     0 |
| University of Mar... |       1 |        0 |        0 |       0 |     0 |
| University of Mas... |       1 |        5 |       32 |       1 |     0 |
| University of Mem... |       1 |        5 |       39 |       5 |     0 |
| University of Min... |       5 |        2 |       45 |       6 |     0 |
| University of New... |       4 |       10 |       19 |      57 |     0 |
| University of Nor... |       6 |        1 |       65 |       9 |     0 |
| University of Nor... |       0 |        1 |       24 |       3 |     0 |
| University of Oregon |       0 |        3 |       35 |       3 |     0 |
| University of Pit... |       5 |        3 |       25 |       2 |     0 |
| University of Sou... |       2 |        8 |      113 |      22 |     0 |
| University of Sou... |       1 |        8 |       48 |       9 |     0 |
| University of Utah   |       0 |        3 |       90 |       0 |     0 |
| University of Vir... |       1 |        0 |       54 |      16 |     0 |
| University of Was... |       3 |        3 |       40 |       1 |     0 |
| Utah State Univer... |       0 |        0 |       12 |       1 |     0 |
| Utah Valley Unive... |       0 |        0 |        7 |       5 |     0 |
| Valencia College     |       0 |        2 |        1 |       3 |     0 |
| Virginia Commonwe... |       3 |        5 |       15 |       4 |     0 |
| Virginia Polytech... |       0 |        3 |       30 |       3 |     0 |
| Walden University    |       0 |        0 |        0 |       0 |     0 |
| Washington State ... |       0 |        2 |       28 |       5 |     0 |
| Wayne County Comm... |       0 |        0 |        0 |       5 |     0 |
| Weber State Unive... |       0 |        0 |       11 |       0 |     0 |
| Western Kentucky ... |       3 |        2 |       32 |       1 |     0 |

In [62]:
burglaries = crime_analysis.order_by('burglary', reverse=True).exclude('manslaughter').exclude('robbery').exclude('forcible')

In [63]:
burglaries.print_table(max_rows = None)

| instname             | total_enr | murder | nonforce | agg_aslt | burglary | ... |
| -------------------- | --------- | ------ | -------- | -------- | -------- | --- |
| University of Cal... |    39,271 |      0 |        0 |        4 |      118 | ... |
| University of Toledo |    67,830 |      0 |        0 |        4 |      118 | ... |
| University of Sou... |    30,721 |      0 |        0 |        8 |      113 | ... |
| Pennsylvania Stat... |    45,628 |      0 |        0 |        6 |      112 | ... |
| Stony Brook Unive... |    23,920 |      0 |        0 |        2 |       96 | ... |
| Arizona State Uni... |   289,016 |      0 |        1 |       27 |       90 | ... |
| University of Utah   |    31,660 |      0 |        0 |        3 |       90 | ... |
| Indiana Universit... |    42,731 |      0 |        0 |       12 |       89 | ... |
| University of Cal... |    63,464 |      0 |        0 |        4 |       86 | ... |
| Michigan State Un... |   191,300 |      0 |        0 |       10 |       77 | ... |
| University of Col... |    44,990 |      0 |        0 |        2 |       75 | ... |
| University of Hou... |   119,460 |      0 |        0 |        3 |       74 | ... |
| University at Buf... |    28,849 |      0 |        0 |        4 |       73 | ... |
| The University of... |    63,294 |      0 |        0 |        3 |       68 | ... |
| Florida State Uni... |    41,087 |      0 |        0 |        8 |       67 | ... |
| Metropolitan Stat... |    23,789 |      0 |        0 |        2 |       66 | ... |
| Rutgers Universit... |    39,950 |      0 |        0 |        5 |       65 | ... |
| University of Nor... |    25,277 |      0 |        0 |        1 |       65 | ... |
| University of Haw... |    40,858 |      0 |        0 |       16 |       64 | ... |
| University of Mar... |    75,262 |      0 |        0 |        4 |       64 | ... |
| Boston University    |    64,878 |      0 |        0 |        3 |       60 | ... |
| Lansing Community... |    41,280 |      0 |        0 |        1 |       60 | ... |
| Northwestern Univ... |   104,795 |      0 |        0 |        0 |       57 | ... |
| Mississippi State... |    40,848 |      0 |        0 |        1 |       56 | ... |
| University of Con... |    51,736 |      0 |        0 |        3 |       54 | ... |
| University of Vir... |   145,782 |      0 |        0 |        0 |       54 | ... |
| University of Geo... |    34,816 |      0 |        0 |        2 |       53 | ... |
| University of Cal... |    54,378 |      0 |        1 |        1 |       52 | ... |
| Indiana Universit... |    61,060 |      0 |        0 |        7 |       51 | ... |
| The University of... |    51,112 |      0 |        0 |        6 |       51 | ... |
| Drexel University    |   149,160 |      0 |        0 |        0 |       50 | ... |
| University of Sou... |   342,090 |      0 |        0 |        1 |       50 | ... |
| Purdue University... |   449,339 |      0 |        0 |        2 |       49 | ... |
| University of Sou... |    39,596 |      0 |        0 |        8 |       48 | ... |
| Iowa State Univer... |    29,611 |      0 |        0 |        8 |       47 | ... |
| Louisiana State U... |    29,718 |      0 |        0 |        9 |       47 | ... |
| University of Ark... |    23,199 |      0 |        0 |        2 |       46 | ... |
| George Washington... |   202,080 |      0 |        0 |        4 |       45 | ... |
| Oklahoma State Un... |    48,780 |      0 |        0 |        1 |       45 | ... |
| University of Min... |   105,114 |      0 |        0 |        2 |       45 | ... |
| Texas State Unive... |    68,174 |      0 |        0 |        5 |       44 | ... |
| University of Ari... |    39,236 |      1 |        0 |        0 |       43 | ... |
| Florida Internati... |    44,616 |      0 |        0 |        4 |       42 | ... |
| San Diego State U... |    30,541 |      0 |        0 |        4 |       42 | ... |
| University of Col... |    32,558 |      0 |        0 |        8 |       42 | ... |
| North Carolina St... |    34,767 |      0 |        0 |        9 |       41 | ... |
| Portland State Un... |    28,584 |      0 |        0 |        0 |       41 | ... |
| San Francisco Sta... |    29,541 |      0 |        0 |        0 |       41 | ... |
| University of Cal... |    72,274 |      0 |        1 |        7 |       40 | ... |
| University of Cal... |    21,685 |      0 |        1 |        3 |       40 | ... |
| University of Was... |    42,444 |      0 |        0 |        3 |       40 | ... |
| University of Kansas |   111,756 |      0 |        0 |        9 |       39 | ... |
| University of Mem... |    90,900 |      0 |        0 |        5 |       39 | ... |
| University of Wis... |    29,350 |      0 |        0 |        0 |       39 | ... |
| University of Mic... |    42,716 |      0 |        0 |        8 |       37 | ... |
| Houston Community... | 1,323,315 |      0 |        0 |        6 |       36 | ... |
| Oregon State Univ... |    24,962 |      0 |        0 |        3 |       36 | ... |
| Syracuse University  |   145,803 |      0 |        0 |        4 |       36 | ... |
| The University of... |   100,317 |      0 |        0 |        2 |       36 | ... |
| University of Nor... |    29,137 |      0 |        0 |        3 |       36 | ... |
| New York University  |   658,665 |      0 |        0 |        0 |       35 | ... |
| Northern Arizona ... |    25,359 |      0 |        0 |        5 |       35 | ... |
| University of Oregon |    73,188 |      0 |        0 |        3 |       35 | ... |
| California State ... |    36,911 |      0 |        0 |        6 |       34 | ... |
| Kennesaw State Un... |    24,175 |      0 |        0 |        0 |       34 | ... |
| Old Dominion Univ... |    24,753 |      0 |        0 |        2 |       34 | ... |
| Fresno City College  |    40,270 |      0 |        0 |        2 |       33 | ... |
| University of Cal... |    20,900 |      0 |        0 |        1 |       32 | ... |
| University of Cen... |   935,440 |      0 |        0 |       12 |       32 | ... |
| University of Mas... |    28,084 |      0 |        0 |        5 |       32 | ... |
| University of Wis... |    41,946 |      0 |        0 |        3 |       32 | ... |
| Western Kentucky ... |   126,216 |      0 |        0 |        2 |       32 | ... |
| Ball State Univer... |    44,294 |      0 |        0 |        0 |       31 | ... |
| George Mason Univ... |    33,320 |      0 |        0 |        0 |       31 | ... |
| Middle Tennessee ... |    26,442 |      0 |        0 |        5 |       30 | ... |
| The University of... |    90,582 |      0 |        0 |        0 |       30 | ... |
| University of Ill... |    88,814 |      0 |        0 |        4 |       30 | ... |
| Virginia Polytech... |   371,232 |      1 |        0 |        3 |       30 | ... |
| California State ... |    21,981 |      0 |        0 |        7 |       29 | ... |
| Texas A & M Unive... |   100,460 |      0 |        0 |        0 |       29 | ... |
| Tulsa Community C... |    80,616 |      0 |        0 |        0 |       29 | ... |
| University of Cal... |    28,593 |      0 |        0 |        6 |       29 | ... |
| University of Okl... |    27,138 |      0 |        0 |        1 |       29 | ... |
| Harvard University   |    54,784 |      0 |        0 |        7 |       28 | ... |
| The University of... |    22,640 |      0 |        0 |        3 |       28 | ... |
| Washington State ... |   109,316 |      0 |        0 |        2 |       28 | ... |
| University of Flo... |    99,178 |      0 |        0 |        6 |       27 | ... |
| Illinois State Un... |    21,310 |      0 |        0 |       21 |       26 | ... |
| University of Del... |    64,467 |      0 |        1 |        3 |       26 | ... |
| Columbia Universi... |   104,200 |      0 |        0 |        4 |       25 | ... |
| University of Pit... |    28,766 |      0 |        0 |        3 |       25 | ... |
| California State ... |    34,870 |      0 |        0 |        1 |       24 | ... |
| San Jose State Un... |    60,472 |      2 |        0 |       13 |       24 | ... |
| University of Nor... |    75,636 |      0 |        0 |        1 |       24 | ... |
| California State ... |    21,107 |      0 |        0 |        0 |       23 | ... |
| University of Nev... |    54,728 |      0 |        0 |        1 |       23 | ... |
| Auburn University    |    25,469 |      0 |        0 |        0 |       22 | ... |
| Florida Atlantic ... |   233,968 |      0 |        0 |        0 |       22 | ... |
| Kansas State Univ... |    47,726 |      0 |        0 |        2 |       22 | ... |
| Northern Illinois... |   114,950 |      0 |        0 |        1 |       22 | ... |
| Ohio State Univer... |    56,867 |      0 |        0 |        0 |       22 | ... |
| West Virginia Uni... |    29,617 |      0 |        0 |        7 |       22 | ... |
| Ohio University-M... |    26,201 |      0 |        0 |        1 |       21 | ... |
| Texas Tech Univer... |   226,289 |      0 |        0 |        3 |       21 | ... |
| University of Iowa   |   119,240 |      0 |        0 |        6 |       20 | ... |
| University of New... |    28,977 |      0 |        0 |       10 |       19 | ... |
| University of Pen... |   148,992 |      0 |        0 |        2 |       19 | ... |
| Georgia Institute... |    41,882 |      0 |        0 |        3 |       18 | ... |
| Wayne State Unive... |   123,060 |      0 |        0 |        2 |       18 | ... |
| East Carolina Uni... |    54,772 |      0 |        0 |        2 |       17 | ... |
| Kent State Univer... |    27,855 |      0 |        0 |        1 |       17 | ... |
| Northeastern Univ... |    26,959 |      0 |        0 |        5 |       17 | ... |
| Colorado State Un... |    30,467 |      0 |        0 |        0 |       16 | ... |
| CUNY Queens College  |    20,993 |      0 |        0 |        0 |       16 | ... |
| Central Michigan ... |    28,194 |      0 |        0 |        2 |       15 | ... |
| DePaul University    |   152,388 |      0 |        0 |        0 |       15 | ... |
| St John's Univers... |   147,469 |      0 |        0 |        0 |       15 | ... |
| University of Cin... |    66,658 |      0 |        0 |        4 |       15 | ... |
| Virginia Commonwe... |    94,881 |      0 |        0 |        5 |       15 | ... |
| Johnson County Co... |    21,020 |      0 |        0 |        1 |       14 | ... |
| University of Ill... |    84,273 |      1 |        0 |        8 |       14 | ... |
| Cornell University   |    21,131 |      0 |        0 |        0 |       13 | ... |
| Eastern Michigan ... |   210,771 |      0 |        0 |        1 |       13 | ... |
| Long Beach City C... |    51,564 |      0 |        0 |        1 |       13 | ... |
| The University of... |    61,936 |      0 |        0 |        6 |       13 | ... |
| University of Ken... |   163,356 |      0 |        0 |        4 |       13 | ... |
| Western Michigan ... |   250,860 |      0 |        1 |        2 |       13 | ... |
| California State ... |    28,016 |      0 |        0 |        0 |       12 | ... |
| Delgado Community... |   163,488 |      0 |        0 |        4 |       12 | ... |
| Utah State Univer... |    26,757 |      0 |        0 |        0 |       12 | ... |
| Towson University    |    21,464 |      0 |        0 |        3 |       11 | ... |
| Weber State Unive... |    25,301 |      0 |        0 |        0 |       11 | ... |
| Brigham Young Uni... |   170,505 |      0 |        0 |        1 |       10 | ... |
| Georgia Southern ... |    20,212 |      0 |        0 |        0 |       10 | ... |
| Grand Canyon Univ... |    40,487 |      0 |        0 |        0 |       10 | ... |
| University of Lou... |    63,456 |      0 |        0 |        0 |       10 | ... |
| University of Mis... |    33,762 |      0 |        0 |        8 |       10 | ... |
| De Anza College      |    24,187 |      0 |        0 |        0 |        9 | ... |
| Salt Lake Communi... |   200,520 |      0 |        0 |        0 |        9 | ... |
| Georgia State Uni... |    64,044 |      0 |        0 |        2 |        8 | ... |
| Santa Monica College |    29,971 |      0 |        0 |        0 |        8 | ... |
| Troy University      |   209,376 |      0 |        0 |        0 |        8 | ... |
| City College of S... |    34,558 |      0 |        0 |        1 |        7 | ... |
| CUNY Hunter College  |   136,932 |      0 |        0 |        0 |        7 | ... |
| East Los Angeles ... |    37,057 |      0 |        0 |        1 |        7 | ... |
| Orange Coast College |    22,654 |      0 |        0 |        0 |        7 | ... |
| Tidewater Communi... |   224,707 |      0 |        0 |        0 |        7 | ... |
| University of Neb... |    24,593 |      0 |        0 |        1 |        7 | ... |
| Utah Valley Unive... |    33,395 |      0 |        0 |        0 |        7 | ... |
| American River Co... |    95,250 |      0 |        2 |        2 |        6 | ... |
| Broward College      |   379,782 |      0 |        0 |        2 |        6 | ... |
| California State ... |   144,624 |      0 |        0 |        7 |        6 | ... |
| Grand Valley Stat... |   123,310 |      0 |        0 |        0 |        6 | ... |
| Mt. San Antonio C... |    28,388 |      0 |        0 |        3 |        6 | ... |
| San Jacinto Commu... |    88,176 |      0 |        0 |        0 |        6 | ... |
| California State ... |    21,284 |      0 |        0 |        2 |        5 | ... |
| College of DuPage    |   157,254 |      0 |        0 |        0 |        5 | ... |
| Liberty University   |    64,096 |      0 |        0 |        1 |        5 | ... |
| Nassau Community ... |    23,550 |      0 |        0 |        0 |        5 | ... |
| Nova Southeastern... |    85,371 |      0 |        1 |        0 |        5 | ... |
| Portland Communit... |   277,056 |      0 |        0 |        6 |        5 | ... |
| Temple University    |   294,840 |      0 |        0 |        4 |        5 | ... |
| University of Akr... |    54,940 |      0 |        0 |        1 |        5 | ... |
| Collin County Com... |    82,779 |      0 |        0 |        0 |        4 | ... |
| Hillsborough Comm... |   141,645 |      0 |        0 |        0 |        4 | ... |
| Instituto de Banc... |    20,876 |      0 |        0 |        1 |        4 | ... |
| Pima Community Co... |   443,628 |      0 |        0 |        2 |        4 | ... |
| Central New Mexic... |   166,062 |      0 |        0 |        9 |        3 | ... |
| Cerritos College     |    21,335 |      0 |        0 |        1 |        3 | ... |
| El Paso Community... |   215,061 |      0 |        0 |        0 |        3 | ... |
| Los Angeles City ... |    21,028 |      0 |        0 |        0 |        3 | ... |
| Missouri State Un... |    20,276 |      0 |        0 |        0 |        3 | ... |
| Montgomery College   |    80,988 |      0 |        0 |        2 |        3 | ... |
| Oakland Community... |   145,790 |      0 |        0 |        0 |        3 | ... |
| Saddleback College   |    22,578 |      0 |        0 |        6 |        3 | ... |
| Santa Ana College    |    30,289 |      0 |        0 |        1 |        3 | ... |
| Austin Community ... | 1,082,400 |      0 |        0 |        1 |        2 | ... |
| Community College... |    81,720 |      0 |        0 |        0 |        2 | ... |
| CUNY Borough of M... |    24,463 |      0 |        0 |        2 |        2 | ... |
| Cuyahoga Communit... |   215,971 |      0 |        0 |        0 |        2 | ... |
| El Camino Communi... |    24,463 |      0 |        0 |        2 |        2 | ... |
| Glendale Communit... |    42,752 |      0 |        0 |        1 |        2 | ... |
| Harrisburg Area C... |   112,975 |      0 |        0 |        2 |        2 | ... |
| Pasadena City Col... |    52,114 |      0 |        0 |        0 |        2 | ... |
| Saint Louis Commu... |   175,200 |      0 |        0 |        0 |        2 | ... |
| Sinclair Communit... |   105,530 |      0 |        0 |        0 |        2 | ... |
| Ashford University   |    74,596 |      0 |        0 |        0 |        1 | ... |
| College of Southe... |   113,151 |      0 |        0 |        0 |        1 | ... |
| Columbus State Co... |   247,368 |      0 |        0 |        0 |        1 | ... |
| Des Moines Area C... |   279,675 |      0 |        0 |        1 |        1 | ... |
| Diablo Valley Col... |    20,310 |      0 |        0 |        1 |        1 | ... |
| Florida State Col... |   246,904 |      0 |        0 |        2 |        1 | ... |
| Ivy Tech Communit... |    42,092 |      0 |        0 |        0 |        1 | ... |
| Johns Hopkins Uni... |   209,960 |      0 |        0 |        0 |        1 | ... |
| Lone Star College... |   378,174 |      0 |        1 |        1 |        1 | ... |
| Los Angeles Pierc... |    20,506 |      0 |        0 |        0 |        1 | ... |
| Mesa Community Co... |    77,085 |      0 |        0 |        4 |        1 | ... |
| Northern Virginia... |   300,264 |      0 |        0 |        2 |        1 | ... |
| Sacramento City C... |    72,318 |      0 |        0 |        0 |        1 | ... |
| San Diego Mesa Co... |    25,504 |      0 |        0 |        0 |        1 | ... |
| Santa Rosa Junior... |    72,597 |      0 |        0 |        1 |        1 | ... |
| Tarrant County Co... |   300,372 |      0 |        0 |        1 |        1 | ... |
| Valencia College     |   341,048 |      0 |        0 |        2 |        1 | ... |
| Capella University   |    36,375 |      0 |        0 |        0 |        0 | ... |
| Central Texas Col... |    80,985 |      0 |        0 |        1 |        0 | ... |
| DeVry University-... |   279,210 |      0 |        0 |        0 |        0 | ... |
| Everest Universit... |    25,537 |      0 |        0 |        0 |        0 | ... |
| Excelsior College    |    35,608 |      0 |        0 |        0 |        0 | ... |
| Front Range Commu... |    82,272 |      0 |        0 |        0 |        0 | ... |
| Full Sail University |    20,160 |      0 |        0 |        2 |        0 | ... |
| Georgia Perimeter... |   134,980 |      0 |        0 |        0 |        0 | ... |
| Kaplan University... |    56,606 |      0 |        0 |        0 |        0 | ... |
| Macomb Community ... |    47,938 |      0 |        0 |        0 |        0 | ... |
| Miami Dade College   |   509,888 |      0 |        0 |        2 |        0 | ... |
| Palm Beach State ... |   117,416 |      0 |        0 |        0 |        0 | ... |
| Palomar College      |    50,854 |      0 |        0 |        2 |        0 | ... |
| Richland College     |    40,000 |      0 |        0 |        1 |        0 | ... |
| Rio Salado College   |   251,090 |      0 |        0 |        0 |        0 | ... |
| San Antonio College  |    25,567 |      0 |        0 |        2 |        0 | ... |
| South Texas College  |    29,604 |      0 |        0 |        2 |        0 | ... |
| Southwestern College |    81,636 |      0 |        0 |        0 |        0 | ... |
| St Petersburg Col... |   265,024 |      0 |        1 |        0 |        0 | ... |
| Suffolk County Co... |   107,148 |      0 |        0 |        0 |        0 | ... |
| The Community Col... |   157,626 |      0 |        0 |        0 |        0 | ... |
| Thomas Edison Sta... |    20,251 |      0 |        0 |        0 |        0 | ... |
| University of Mar... |   256,278 |      0 |        0 |        0 |        0 | ... |
| Walden University    |    48,982 |      0 |        0 |        0 |        0 | ... |
| Wayne County Comm... |   122,640 |      0 |        0 |        0 |        0 | ... |

Would be interested as to why these top four universities for burgalries are what they are, as their total enrollment is not as high as others.

In [69]:
manslaughters = crime_analysis.order_by('manslaughter', reverse=True)

In [70]:
manslaughters.print_table(max_rows=None)

| instname             | total_enr | murder | manslaughter | forcible | nonforce | ... |
| -------------------- | --------- | ------ | ------------ | -------- | -------- | --- |
| Florida State Uni... |    41,087 |      0 |         True |        2 |        0 | ... |
| American River Co... |    95,250 |      0 |        False |        1 |        2 | ... |
| Arizona State Uni... |   289,016 |      0 |        False |       17 |        1 | ... |
| Ashford University   |    74,596 |      0 |        False |        2 |        0 | ... |
| Auburn University    |    25,469 |      0 |        False |        1 |        0 | ... |
| Austin Community ... | 1,082,400 |      0 |        False |        0 |        0 | ... |
| Ball State Univer... |    44,294 |      0 |        False |        8 |        0 | ... |
| Boston University    |    64,878 |      0 |        False |        6 |        0 | ... |
| Brigham Young Uni... |   170,505 |      0 |        False |        0 |        0 | ... |
| Broward College      |   379,782 |      0 |        False |        0 |        0 | ... |
| California State ... |    21,107 |      0 |        False |        7 |        0 | ... |
| California State ... |    21,981 |      0 |        False |        1 |        0 | ... |
| California State ... |   144,624 |      0 |        False |        0 |        0 | ... |
| California State ... |    34,870 |      0 |        False |        3 |        0 | ... |
| California State ... |    21,284 |      0 |        False |        1 |        0 | ... |
| California State ... |    36,911 |      0 |        False |        1 |        0 | ... |
| California State ... |    28,016 |      0 |        False |        2 |        0 | ... |
| Capella University   |    36,375 |      0 |        False |        0 |        0 | ... |
| Central Michigan ... |    28,194 |      0 |        False |        5 |        0 | ... |
| Central New Mexic... |   166,062 |      0 |        False |        3 |        0 | ... |
| Central Texas Col... |    80,985 |      0 |        False |        0 |        0 | ... |
| Cerritos College     |    21,335 |      0 |        False |        1 |        0 | ... |
| City College of S... |    34,558 |      0 |        False |        1 |        0 | ... |
| College of DuPage    |   157,254 |      0 |        False |        0 |        0 | ... |
| College of Southe... |   113,151 |      0 |        False |        2 |        0 | ... |
| Collin County Com... |    82,779 |      0 |        False |        0 |        0 | ... |
| Colorado State Un... |    30,467 |      0 |        False |        4 |        0 | ... |
| Columbia Universi... |   104,200 |      0 |        False |        4 |        0 | ... |
| Columbus State Co... |   247,368 |      0 |        False |        0 |        0 | ... |
| Community College... |    81,720 |      0 |        False |        0 |        0 | ... |
| Cornell University   |    21,131 |      0 |        False |        7 |        0 | ... |
| CUNY Borough of M... |    24,463 |      0 |        False |        2 |        0 | ... |
| CUNY Hunter College  |   136,932 |      0 |        False |        0 |        0 | ... |
| CUNY Queens College  |    20,993 |      0 |        False |        0 |        0 | ... |
| Cuyahoga Communit... |   215,971 |      0 |        False |        3 |        0 | ... |
| De Anza College      |    24,187 |      0 |        False |        0 |        0 | ... |
| Delgado Community... |   163,488 |      0 |        False |        0 |        0 | ... |
| DePaul University    |   152,388 |      0 |        False |        1 |        0 | ... |
| Des Moines Area C... |   279,675 |      0 |        False |        0 |        0 | ... |
| DeVry University-... |   279,210 |      0 |        False |        0 |        0 | ... |
| Diablo Valley Col... |    20,310 |      0 |        False |        0 |        0 | ... |
| Drexel University    |   149,160 |      0 |        False |        5 |        0 | ... |
| East Carolina Uni... |    54,772 |      0 |        False |        9 |        0 | ... |
| East Los Angeles ... |    37,057 |      0 |        False |        0 |        0 | ... |
| Eastern Michigan ... |   210,771 |      0 |        False |        4 |        0 | ... |
| El Camino Communi... |    24,463 |      0 |        False |        0 |        0 | ... |
| El Paso Community... |   215,061 |      0 |        False |        0 |        0 | ... |
| Everest Universit... |    25,537 |      0 |        False |        0 |        0 | ... |
| Excelsior College    |    35,608 |      0 |        False |        0 |        0 | ... |
| Florida Atlantic ... |   233,968 |      0 |        False |        1 |        0 | ... |
| Florida Internati... |    44,616 |      0 |        False |        3 |        0 | ... |
| Florida State Col... |   246,904 |      0 |        False |        0 |        0 | ... |
| Fresno City College  |    40,270 |      0 |        False |        0 |        0 | ... |
| Front Range Commu... |    82,272 |      0 |        False |        0 |        0 | ... |
| Full Sail University |    20,160 |      0 |        False |        0 |        0 | ... |
| George Mason Univ... |    33,320 |      0 |        False |        8 |        0 | ... |
| George Washington... |   202,080 |      0 |        False |       16 |        0 | ... |
| Georgia Institute... |    41,882 |      0 |        False |        5 |        0 | ... |
| Georgia Perimeter... |   134,980 |      0 |        False |        0 |        0 | ... |
| Georgia Southern ... |    20,212 |      0 |        False |        3 |        0 | ... |
| Georgia State Uni... |    64,044 |      0 |        False |        4 |        0 | ... |
| Glendale Communit... |    42,752 |      0 |        False |        0 |        0 | ... |
| Grand Canyon Univ... |    40,487 |      0 |        False |        1 |        0 | ... |
| Grand Valley Stat... |   123,310 |      0 |        False |        2 |        0 | ... |
| Harrisburg Area C... |   112,975 |      0 |        False |        1 |        0 | ... |
| Harvard University   |    54,784 |      0 |        False |       21 |        0 | ... |
| Hillsborough Comm... |   141,645 |      0 |        False |        0 |        0 | ... |
| Houston Community... | 1,323,315 |      0 |        False |        0 |        0 | ... |
| Illinois State Un... |    21,310 |      0 |        False |        2 |        0 | ... |
| Indiana Universit... |    42,731 |      0 |        False |       11 |        0 | ... |
| Indiana Universit... |    61,060 |      0 |        False |        2 |        0 | ... |
| Instituto de Banc... |    20,876 |      0 |        False |        0 |        0 | ... |
| Iowa State Univer... |    29,611 |      0 |        False |        6 |        0 | ... |
| Ivy Tech Communit... |    42,092 |      0 |        False |        0 |        0 | ... |
| Johns Hopkins Uni... |   209,960 |      0 |        False |        0 |        0 | ... |
| Johnson County Co... |    21,020 |      0 |        False |        1 |        0 | ... |
| Kansas State Univ... |    47,726 |      0 |        False |        7 |        0 | ... |
| Kaplan University... |    56,606 |      0 |        False |        0 |        0 | ... |
| Kennesaw State Un... |    24,175 |      0 |        False |        2 |        0 | ... |
| Kent State Univer... |    27,855 |      0 |        False |        3 |        0 | ... |
| Lansing Community... |    41,280 |      0 |        False |        0 |        0 | ... |
| Liberty University   |    64,096 |      0 |        False |        4 |        0 | ... |
| Lone Star College... |   378,174 |      0 |        False |        0 |        1 | ... |
| Long Beach City C... |    51,564 |      0 |        False |        0 |        0 | ... |
| Los Angeles City ... |    21,028 |      0 |        False |        0 |        0 | ... |
| Los Angeles Pierc... |    20,506 |      0 |        False |        4 |        0 | ... |
| Louisiana State U... |    29,718 |      0 |        False |        2 |        0 | ... |
| Macomb Community ... |    47,938 |      0 |        False |        0 |        0 | ... |
| Mesa Community Co... |    77,085 |      0 |        False |        0 |        0 | ... |
| Metropolitan Stat... |    23,789 |      0 |        False |        1 |        0 | ... |
| Miami Dade College   |   509,888 |      0 |        False |        0 |        0 | ... |
| Michigan State Un... |   191,300 |      0 |        False |       15 |        0 | ... |
| Middle Tennessee ... |    26,442 |      0 |        False |        4 |        0 | ... |
| Mississippi State... |    40,848 |      0 |        False |        1 |        0 | ... |
| Missouri State Un... |    20,276 |      0 |        False |        0 |        0 | ... |
| Montgomery College   |    80,988 |      0 |        False |        4 |        0 | ... |
| Mt. San Antonio C... |    28,388 |      0 |        False |        1 |        0 | ... |
| Nassau Community ... |    23,550 |      0 |        False |        1 |        0 | ... |
| New York University  |   658,665 |      0 |        False |        1 |        0 | ... |
| North Carolina St... |    34,767 |      0 |        False |        7 |        0 | ... |
| Northeastern Univ... |    26,959 |      0 |        False |        6 |        0 | ... |
| Northern Arizona ... |    25,359 |      0 |        False |       13 |        0 | ... |
| Northern Illinois... |   114,950 |      0 |        False |        4 |        0 | ... |
| Northern Virginia... |   300,264 |      0 |        False |        2 |        0 | ... |
| Northwestern Univ... |   104,795 |      0 |        False |        3 |        0 | ... |
| Nova Southeastern... |    85,371 |      0 |        False |        2 |        1 | ... |
| Oakland Community... |   145,790 |      0 |        False |        2 |        0 | ... |
| Ohio State Univer... |    56,867 |      0 |        False |       28 |        0 | ... |
| Ohio University-M... |    26,201 |      0 |        False |        8 |        0 | ... |
| Oklahoma State Un... |    48,780 |      0 |        False |       11 |        0 | ... |
| Old Dominion Univ... |    24,753 |      0 |        False |        7 |        0 | ... |
| Orange Coast College |    22,654 |      0 |        False |        1 |        0 | ... |
| Oregon State Univ... |    24,962 |      0 |        False |        3 |        0 | ... |
| Palm Beach State ... |   117,416 |      0 |        False |        0 |        0 | ... |
| Palomar College      |    50,854 |      0 |        False |        1 |        0 | ... |
| Pasadena City Col... |    52,114 |      0 |        False |        2 |        0 | ... |
| Pennsylvania Stat... |    45,628 |      0 |        False |       24 |        0 | ... |
| Pima Community Co... |   443,628 |      0 |        False |        0 |        0 | ... |
| Portland Communit... |   277,056 |      0 |        False |        5 |        0 | ... |
| Portland State Un... |    28,584 |      0 |        False |        8 |        0 | ... |
| Purdue University... |   449,339 |      0 |        False |        7 |        0 | ... |
| Richland College     |    40,000 |      0 |        False |        0 |        0 | ... |
| Rio Salado College   |   251,090 |      0 |        False |        0 |        0 | ... |
| Rutgers Universit... |    39,950 |      0 |        False |       12 |        0 | ... |
| Sacramento City C... |    72,318 |      0 |        False |        1 |        0 | ... |
| Saddleback College   |    22,578 |      0 |        False |        1 |        0 | ... |
| Saint Louis Commu... |   175,200 |      0 |        False |        0 |        0 | ... |
| Salt Lake Communi... |   200,520 |      0 |        False |        1 |        0 | ... |
| San Antonio College  |    25,567 |      0 |        False |        1 |        0 | ... |
| San Diego Mesa Co... |    25,504 |      0 |        False |        0 |        0 | ... |
| San Diego State U... |    30,541 |      0 |        False |        6 |        0 | ... |
| San Francisco Sta... |    29,541 |      0 |        False |        4 |        0 | ... |
| San Jacinto Commu... |    88,176 |      0 |        False |        0 |        0 | ... |
| San Jose State Un... |    60,472 |      2 |        False |        3 |        0 | ... |
| Santa Ana College    |    30,289 |      0 |        False |        0 |        0 | ... |
| Santa Monica College |    29,971 |      0 |        False |        0 |        0 | ... |
| Santa Rosa Junior... |    72,597 |      0 |        False |        0 |        0 | ... |
| Sinclair Communit... |   105,530 |      0 |        False |        0 |        0 | ... |
| South Texas College  |    29,604 |      0 |        False |        0 |        0 | ... |
| Southwestern College |    81,636 |      0 |        False |        0 |        0 | ... |
| St John's Univers... |   147,469 |      0 |        False |        5 |        0 | ... |
| St Petersburg Col... |   265,024 |      0 |        False |        0 |        1 | ... |
| Stony Brook Unive... |    23,920 |      0 |        False |       13 |        0 | ... |
| Suffolk County Co... |   107,148 |      0 |        False |        0 |        0 | ... |
| Syracuse University  |   145,803 |      0 |        False |       12 |        0 | ... |
| Tarrant County Co... |   300,372 |      0 |        False |        0 |        0 | ... |
| Temple University    |   294,840 |      0 |        False |        4 |        0 | ... |
| Texas A & M Unive... |   100,460 |      0 |        False |        3 |        0 | ... |
| Texas State Unive... |    68,174 |      0 |        False |        3 |        0 | ... |
| Texas Tech Univer... |   226,289 |      0 |        False |        3 |        0 | ... |
| The Community Col... |   157,626 |      0 |        False |        1 |        0 | ... |
| The University of... |    63,294 |      0 |        False |        3 |        0 | ... |
| The University of... |    90,582 |      0 |        False |        4 |        0 | ... |
| The University of... |   100,317 |      0 |        False |        2 |        0 | ... |
| The University of... |    51,112 |      0 |        False |        2 |        0 | ... |
| The University of... |    22,640 |      0 |        False |        5 |        0 | ... |
| The University of... |    61,936 |      0 |        False |        2 |        0 | ... |
| Thomas Edison Sta... |    20,251 |      0 |        False |        0 |        0 | ... |
| Tidewater Communi... |   224,707 |      0 |        False |        0 |        0 | ... |
| Towson University    |    21,464 |      0 |        False |        7 |        0 | ... |
| Troy University      |   209,376 |      0 |        False |        0 |        0 | ... |
| Tulsa Community C... |    80,616 |      0 |        False |        0 |        0 | ... |
| University at Buf... |    28,849 |      0 |        False |        3 |        0 | ... |
| University of Akr... |    54,940 |      0 |        False |        5 |        0 | ... |
| University of Ari... |    39,236 |      1 |        False |        3 |        0 | ... |
| University of Ark... |    23,199 |      0 |        False |        5 |        0 | ... |
| University of Cal... |    72,274 |      0 |        False |       30 |        1 | ... |
| University of Cal... |    63,464 |      0 |        False |       24 |        0 | ... |
| University of Cal... |    54,378 |      0 |        False |        6 |        1 | ... |
| University of Cal... |    39,271 |      0 |        False |        8 |        0 | ... |
| University of Cal... |    20,900 |      0 |        False |        5 |        0 | ... |
| University of Cal... |    28,593 |      0 |        False |        6 |        0 | ... |
| University of Cal... |    21,685 |      0 |        False |        7 |        1 | ... |
| University of Cen... |   935,440 |      0 |        False |        6 |        0 | ... |
| University of Cin... |    66,658 |      0 |        False |        9 |        0 | ... |
| University of Col... |    32,558 |      0 |        False |        6 |        0 | ... |
| University of Col... |    44,990 |      0 |        False |        1 |        0 | ... |
| University of Con... |    51,736 |      0 |        False |        8 |        0 | ... |
| University of Del... |    64,467 |      0 |        False |        3 |        1 | ... |
| University of Flo... |    99,178 |      0 |        False |       10 |        0 | ... |
| University of Geo... |    34,816 |      0 |        False |        5 |        0 | ... |
| University of Haw... |    40,858 |      0 |        False |       12 |        0 | ... |
| University of Hou... |   119,460 |      0 |        False |        6 |        0 | ... |
| University of Ill... |    84,273 |      1 |        False |        9 |        0 | ... |
| University of Ill... |    88,814 |      0 |        False |        5 |        0 | ... |
| University of Iowa   |   119,240 |      0 |        False |       10 |        0 | ... |
| University of Kansas |   111,756 |      0 |        False |        4 |        0 | ... |
| University of Ken... |   163,356 |      0 |        False |        5 |        0 | ... |
| University of Lou... |    63,456 |      0 |        False |        0 |        0 | ... |
| University of Mar... |    75,262 |      0 |        False |        4 |        0 | ... |
| University of Mar... |   256,278 |      0 |        False |        0 |        0 | ... |
| University of Mas... |    28,084 |      0 |        False |       13 |        0 | ... |
| University of Mem... |    90,900 |      0 |        False |        2 |        0 | ... |
| University of Mic... |    42,716 |      0 |        False |       14 |        0 | ... |
| University of Min... |   105,114 |      0 |        False |       12 |        0 | ... |
| University of Mis... |    33,762 |      0 |        False |       11 |        0 | ... |
| University of Neb... |    24,593 |      0 |        False |        3 |        0 | ... |
| University of Nev... |    54,728 |      0 |        False |        1 |        0 | ... |
| University of New... |    28,977 |      0 |        False |        2 |        0 | ... |
| University of Nor... |    29,137 |      0 |        False |       12 |        0 | ... |
| University of Nor... |    25,277 |      0 |        False |        2 |        0 | ... |
| University of Nor... |    75,636 |      0 |        False |        2 |        0 | ... |
| University of Okl... |    27,138 |      0 |        False |       13 |        0 | ... |
| University of Oregon |    73,188 |      0 |        False |        8 |        0 | ... |
| University of Pen... |   148,992 |      0 |        False |       12 |        0 | ... |
| University of Pit... |    28,766 |      0 |        False |        4 |        0 | ... |
| University of Sou... |    30,721 |      0 |        False |        1 |        0 | ... |
| University of Sou... |    39,596 |      0 |        False |        1 |        0 | ... |
| University of Sou... |   342,090 |      0 |        False |        8 |        0 | ... |
| University of Toledo |    67,830 |      0 |        False |        2 |        0 | ... |
| University of Utah   |    31,660 |      0 |        False |        5 |        0 | ... |
| University of Vir... |   145,782 |      0 |        False |       13 |        0 | ... |
| University of Was... |    42,444 |      0 |        False |        5 |        0 | ... |
| University of Wis... |    41,946 |      0 |        False |       24 |        0 | ... |
| University of Wis... |    29,350 |      0 |        False |        3 |        0 | ... |
| Utah State Univer... |    26,757 |      0 |        False |        3 |        0 | ... |
| Utah Valley Unive... |    33,395 |      0 |        False |        3 |        0 | ... |
| Valencia College     |   341,048 |      0 |        False |        0 |        0 | ... |
| Virginia Commonwe... |    94,881 |      0 |        False |        6 |        0 | ... |
| Virginia Polytech... |   371,232 |      1 |        False |       14 |        0 | ... |
| Walden University    |    48,982 |      0 |        False |        0 |        0 | ... |
| Washington State ... |   109,316 |      0 |        False |        8 |        0 | ... |

Florida State University is the only university on the list where 'manslaughter' = True. Definitely worth investigating.

In [85]:
crimes = crime_analysis.order_by('murder')
summary = crimes.aggregate([
    ('manslaughter', agate.Count()),
    ('mean_murder', agate.Mean('murder')),
    ('mean_agg_aslt', agate.Mean('agg_aslt'))
])

In [86]:
summary.print_table(max_rows=None)

AttributeError: 'collections.OrderedDict' object has no attribute 'print_table'

In [94]:
mean_burglaries = crime_analysis.aggregate(agate.Mean('burglary'))

In [95]:
print(mean_burglaries)

23.79385964912280701754385965

'Burglaries' is really high.

In [96]:
mean_arson = crime_analysis.aggregate(agate.Mean('arson'))

In [97]:
print(mean_arson)

0.8201754385964912280701754386

In [98]:
mean_murder = crime_analysis.aggregate(agate.Mean('murder'))

In [99]:
print(mean_murder)

0.02192982456140350877192982456

In [100]:
mean_robbery = crime_analysis.aggregate(agate.Mean('robbery'))

In [101]:
print(mean_robbery)

1.728070175438596491228070175

## Other notes

Again, there is no right answer here. There is no requirement for how long or involved the analysis has to be. You could even use my work above as a starting point.

Just use this an an excuse to explore tools like [Pandas](http://pandas.pydata.org/) and [Seaborn](https://seaborn.pydata.org/), or check out other analysis tools ([agate](https://agate.readthedocs.io/en/1.6.0/), [ggplot](http://ggplot.yhathq.com)) that you might find interesting. 

Look at examples, use Google and explore the documentation for each of these tools. Or if there's something you can't figure out how to do, just ask me!